### ISSUE TITLE
Allow ItemRenderers to set `key` on themselves

### ISSUE THREAD

**Issue by NeekSandhu** [bvaughn/react-window#107]
I'm working on a FileTree viewer using `react-window`. In my implementation, the top-down flat structure is managed in a `UInt32Array` for max efficiency. This approach has few hiccups that requires a bit of math to resolve a given `index` to `FileEntry` object that we can put to use. For rendering an item, that math work is inevitable. But having to do the same math for `itemKey` gets a bit expensive.

I think it'd be lovely if the math I'm gonna do for rendering an item, might as well be put to use to apply `key` property. And `react-window` can "extract" the key from there if `itemKey` is not specified.

Example:

```javascript
const Row = ({ index, style }) => {
  const fileEntry = this.getItemAtIndex(index) // heavy math work

  // Note the `key` prop on `div` below. Maybe `react-window` can use this?
  return <div key={fileEntry.id} style={style}> { /* ... */ } </div>
}

<FixedSizeList
  width={300}
  height={500}
  itemCount={this.uint32.length}
  itemHeight={22}>
  {Row}
<FixedSizeList />
```

Also one might say, you can memoize `this.getItemAtIndex`, but trust me, memoizing is not viable as data must be computed at each run individually.

**Comment by bvaughn** [comment]
What you're describing isn't possible with how React works. A `key` prop will have _necessarily_ already been attached to the `Row` item before the code where your "_heavy math work_" comment is will run. React uses that `key` to decide when to _update_ vs _recreate_ an element instance.

> Also one might say, you can memoize `this.getItemAtIndex`, but trust me, memoizing is not viable as data must be computed at each run individually.

I don't really understand this comment. If you're using the `fileEntry` value above as your `key`, you're going to need to compute/recompute it _very often_ anyway (e.g. in response to every "scroll" event) since React needs to use that value each render. If it's really _that heavy_ to compute, I suggest just letting `react-window` use the default, index-based `key`. This should work well enough unless your items are regularly being inserted, deleted, or moved within the list.

Also, I would suggest considering either `PureComponent` ([as described here](https://react-window.now.sh/#/examples/list/memoized-list-items)) or the newer [`React.memo`](https://reactjs.org/docs/react-api.html#reactmemo) to reduce the chance of unnecessary re-renders.

If for some reason you really need to use the `fileEntry` value as your `key`, then I believe you might be able to "memoize" it in another way though– using the `itemData` prop to share it with your item renderer. You could store a map of index to `key` somewhere and pass this down via the `itemData` prop as described in the docs so that the `Row` could just re-use the value.

Anyway, I may be misunderstanding some of the details of your app because it seems a little confusing. Hope this response was helpful though!
