### ISSUE TITLE
Use full viewport

### ISSUE THREAD

**Issue by JohannesKlauss** [bvaughn/react-window#115]
Is there a possibility to tell react-window to use the full viewport of the wrapping container? Why can't I just set the `width` and `height` parameters to `100%`?

**Comment by bvaughn** [comment]
> Is there a possibility to tell react-window to use the full viewport of the wrapping container?

No, not without using something like [`react-virtualized-auto-sizer`](https://www.npmjs.com/package/react-virtualized-auto-sizer).

> Why can't I just set the width and height parameters to 100%?

Because APIs like [`ResizeObserver `](https://developers.google.com/web/updates/2016/10/resizeobserver) the [aren't very well supported yet](https://caniuse.com/#feat=resizeobserver)
