### ISSUE TITLE
[Question] : Migration from react-virtualized with custom cellRangeRenderer

### ISSUE THREAD

**Issue by Julienng** [bvaughn/react-window#124]
Hi, I tried to migrate from `react-virtualized` to `react-window` but I have a problem to figure out the best way to handle "expandable row" (like [here](https://react-table.js.org/#/story/sub-components)).

I use a Grid with custom a `cellRangeRenderer` with react-virtualized to dynamically add the expandable component.

**Comment by bvaughn** [comment]
Hello! 😄 

For this type of question, I suggest using Stack Overflow with a [#react-window tag](http://stackoverflow.com/questions/tagged/react-window). Issues are reserved for bug reports and feature-requests.

This helps keep the project somewhat more maintainable for me _and_ hopefully gets you an answer faster (since more people check those places than monitor GitHub issues). 😄

You'll want to start off with either [`VariableSizeList `](https://react-window.now.sh/#/examples/list/variable-size) or [`VariableSizeGrid`](https://react-window.now.sh/#/examples/grid/variable-size). Also when you post, I suggest showing what you've tried (e.g. link to a Code Sandbox or something) rather than just asking an open ended question like this.

**Comment by carlosagsmendes** [comment]
@Julienng there's a [working example of expandable rows](https://codesandbox.io/s/kmzrylpx7o)
