### ISSUE TITLE
Click events not always registering for Rows when scrolling fast

### ISSUE THREAD

**Issue by johot** [bvaughn/react-window#128]
So I have created a basic ListBox using `react-window` and everything is rendering great!

One problem I have however is that if I scroll the list and right after scrolling click on an item it's click handler (a `div` in this case) is not always invoked.

My guess is that I click before the item has been properly rendered and placed on the screen. Does this sound plausible?

Maybe if the `FixedSizeList` could have it's own click handler that could calculate which items should have been clicked in case it has not been rendered fully yet?

Is there any strategy or workaround for these kinds of problems? Is it a known issue?

Thanks for a great library!

**Comment by bvaughn** [comment]
This library intentionally [disables `pointer-events` while a user is scrolling](https://github.com/bvaughn/react-window/blob/a22f3e983dd3d15da1e51230189c928ad93f9bbb/src/createListComponent.js#L297) to improve performance. This is a common technique in windowing libraries (see [react-virtualized](https://github.com/bvaughn/react-virtualized/blob/c0e6e687434998ae6d6c7f8cd4ecbc9f11309f7b/source/Grid/Grid.js#L605), [react-infinite's `Infinite`](https://github.com/seatgeek/react-infinite/blob/6c38c2ef3c473394a57c80c06339754e621f2909/src/react-infinite.jsx#L420)and [fixed-data-table's `FixedDataTableBufferedRows`](https://github.com/facebook/fixed-data-table/blob/5cbf487dd038c2b741cd0298922c1c30dacb38d7/src/FixedDataTableBufferedRows.react.js#L161)).

To my knowledge, this is still commonly done to improve performance (although admittedly it has been a while since I've looked into this so it's possible things have changed– in which case, I'd welcome any updated resources you may have).

For the time being though, I'm going to close this issue as I don't plan on changing the current behavior. We can continue to chat here though if you have more ideas or questions. 😄

**Comment by bvaughn** [comment]
I should add that I currently reset the is-scrolling state [after a 150ms delay](https://github.com/bvaughn/react-window/blob/a22f3e983dd3d15da1e51230189c928ad93f9bbb/src/createListComponent.js#L102) so the window of time in which a click event is not handled should be small.

**Comment by johot** [comment]
The workaround is basically just this:
```
export function Row(props) {
  return (
    <div onClick={() => alert("Clicked")} style={{ pointerEvents: "auto" }}>
      Click me
    </div>
  );
}
```

A first step would be to just add it to the FAQ I guess (in `Readme.md`?). Another thing I would love to see in the FAQ is something about `AutoSizer`, had to dig around the issues to find that info also :)

**Comment by bvaughn** [comment]
Cool, thanks. :) PRs to the README are always welcome too~

**Comment by johot** [comment]
Sure thing, will look into it :D

**Comment by heyimalex** [comment]
@johot [Here's a codesandbox](https://codesandbox.io/s/zn61kz9nj4) that kinda does what you were talking about with the virtualized onClick but outside of the library. I didn't think too hard about it but it seems to work? It tracks scroll position through the `onScroll` callback, and attaches an `onClick` handler to a container div that calculates the item under the cursor.

**Comment by chrisnojima** [comment]
Just want to chime in that I just got a bug report about this in our app and am now applying this as a workaround

**Comment by withintheruins14** [comment]
I would like to chime in and say that I am applying this patch too, as 150 ms is not quick enough for my use case

**Comment by Amaranthusss** [comment]
It's now the end of 2023, and I've encountered the exact same issue. I've spent many hours trying to optimize my code, and now I know that simply setting pointerEvents to 'auto' was all that was needed :). If I had pushed the changes with ignoring events during fast scrolling, someone would surely have reported it as a bug.

@johot Thanks for the workaround :)

**Comment by johot** [comment]
Glad to have helped! 😊
