### ISSUE TITLE
List: broken rendering if scrolling while `display: none` is set + not scrolling to the right element

### ISSUE THREAD

**Issue by fabiospampinato** [bvaughn/react-window#136]
Steps to reproduce:

- Have a list
- Scroll it
- Filter it
- Even if the new filtered list is not long enough to be scrollable `react-window` still thinks that it is scrolled, and some rows might not get rendered

I've made a video showcasing this [here](https://imgur.com/a/a0QSIDP).

Until this is fixed I think I'll either have to render the list twice by forcing an update of `scrollOffset` by triggering a `scroll` event, or manually setting `scrollTop = 0` before each filtering round or something.

[scroll_offset.mp4.zip](https://github.com/bvaughn/react-window/files/2871324/scroll_offset.mp4.zip)

**Comment by fabiospampinato** [comment]
If anyone stumbles upon this, I've fixed it this way: 1) add the proper refs and then 2) add this

```ts

  componentDidUpdate () {

    if ( this.listRef.current && this.innerRef.current ) {

      const {scrollOffset} = this.listRef.current.state,
            {scrollTop} = this.innerRef.current;

      if ( scrollOffset !== scrollTop ) {

        this.listRef.current.setState ({ scrollOffset: scrollTop });

      }

    }

  }
```

If there's a better solution I haven't found it.

**Comment by heyimalex** [comment]
Could you make a code sandbox that replicates this? I [tried](https://codesandbox.io/s/my89mrn76j) but it seems like it works unless I'm misunderstanding.

**Comment by fabiospampinato** [comment]
@heyimalex I can't reproduce it either on codesandbox 🤷‍♀️ I'll let you guys now when the code I've used for the screencast is published, perhaps you could reproduce it with that.

**Comment by bvaughn** [comment]
Looks like something funky is going on with your params (like maybe you aren't updating the `itemCount` or something). Unless you can provide a repro, I can't really help here.

**Comment by fabiospampinato** [comment]
I couldn't reproduce this on codesandbox, but I'm still seeing it. The best that I can offer at the moment is the code of the Electron app I've recorded the [video](https://imgur.com/a/a0QSIDP) on: 

- The code is [here](https://github.com/notable/notable).
- [This](https://github.com/notable/notable/blob/3642fd343a9ac5a899e71517bdbd18ebf32b7328/src/renderer/components/main/structures/tree.tsx#L51-L66) function needs to be commented out, as I'm using it to work around the bug.
- [Here](https://github.com/notable/notable/blob/master/.github/CONTRIBUTING.md#submit-a-pull-request) there are the building instructions (if some of those scripts fail, as they are not all cross-platform, it should probably still be ok).
- Then just to do the same thing I'm doing in the [video](https://imgur.com/a/a0QSIDP), namely scroll the list and cause an update.

If there's something that you'd like me to try on my end I'd be happy to do so.

**Comment by fabiospampinato** [comment]
@bvaughn I can no longer reproduce this in v1.8.1, perhaps it got fixed accidentally.

**Comment by bvaughn** [comment]
😅

**Comment by fabiospampinato** [comment]
Wait now I can reproduce it again but doing something different 🤔 If I do the following:

- Scroll the list down
- Hide the whole node via CSS (`display: none`)
- Perform a `#scrollToItem ( 0, 'auto' )`
- Re-show the node (removing `display: none`)

The list looks broken. I'll try to craft a self-contained example in codesandbox.

**Comment by fabiospampinato** [comment]
@bvaughn here's a snippet that reproduces the problem for me: https://codesandbox.io/s/j2w84zr943 weirdly enough for me this reproduces the issue on Chrome but not on Firefox. Hope that helps.

**Comment by fabiospampinato** [comment]
@bvaughn can this issue be re-opened now that there's a codesandbox that reproduces the issue?

**Comment by bvaughn** [comment]
Sure, I'll re-open it. I won't be able to look into it any time soon though, so if it's something you want to get fixed, shoot me a PR? Preferably with at least one new test that accompanies the fix 😄

**Comment by bvaughn** [comment]
Doesn't look like the issue title matches the repro case anymore though. Mind updating it given the newer info?

**Comment by fabiospampinato** [comment]
Thanks, I'll try to give it a shot in about 2 weeks time 👍 

Btw I apologize for my comment in the other issue about the "ugliness" of the `outerElementType` prop, I think I'm not writing code the React way some times, and in hindsight that prop is actually pretty powerful.

**Comment by bvaughn** [comment]
Hey no problem 😄 I don't remember which comment you're referring to, but I appreciate this follow up comment!

**Comment by chinmay17** [comment]
Hey!
@fabiospampinato This is happening because of `display: none`. As the following code https://github.com/bvaughn/react-window/blob/master/src/createListComponent.js#L277
fails to update the scrollTop as the element is no longer present in the document.

As a workaround, you can use `visibility` and it works as expected. https://codesandbox.io/s/bvaughnreact-window-fixed-size-list-vertical-wqquo

I believe **there's no bug w.r.t. react-window** here.

Eagerly waiting for suggestions/views/comments.

**Comment by chinmay17** [comment]
Hey @fabiospampinato Even in Firefox, the scroll is not what you intend it to be. There's an extra scroll event when the display is set back to block, which leads to newer render. As per your code, the list should be showing the items from 15-34 but in Firefox it shows the items 30-49 because of the extra scroll event.

**Comment by fabiospampinato** [comment]
> the scroll is not what you intend it to be

I'm not sure what this means.

I'm not sure I'm following your argumentation, are you saying that Firefox is triggering an extra scroll event when it shouldn't? Or that Chrome should trigger one and it isn't?

**Comment by chinmay17** [comment]
1.
> This is happening because of display: none. As the following code https://github.com/bvaughn/react-window/blob/master/src/createListComponent.js#L277
> fails to update the scrollTop

This holds true for Chrome as well as Firefox.

2.
As per your codesandbox
```

  setTimeout(() => listRef.current.scrollToItem(49, "auto"), 1000);
  setTimeout(() => (outerRef.current.style.display = "none"), 2000);
  setTimeout(() => listRef.current.scrollToItem(15, "auto"), 3000);
  setTimeout(() => (outerRef.current.style.display = "block"), 4000);

```

You want the list to be scrolled to item 15 - listRef.current.scrollToItem(15, "auto")
But even in Firefox, you can't see it happening because of `1.`

3.
The only difference between Chrome and Firefox is
>There's an extra scroll event when the display is set back to block, which leads to newer render

Whether there's an extra scroll event or not, the intention of scrolling the list to item 15 is not achieved and that's because you're trying to scroll to an index after setting the scroll container to display none.

If `visibility: hidden` is not doable, then you can probably try a combination of position absolute and visibility: hidden. Essentially, extracting it out from the layout in a way so that it simulates the work of display: none -- https://codesandbox.io/s/bvaughnreact-window-fixed-size-list-vertical-z80z1

**Comment by fabiospampinato** [comment]
I think there are 2 issues here:

1. The list looks broken in Chrome, and that should basically never happen, do we agree with that? If that's happening because I'm calling `scrollToItem` while the list has `display: none` then the library should detect that and probably do nothing if the list is `display: none`. 
  - Also you're saying this is not happening in Firefox because it triggers an extra "scroll" event, and in fact that's what I'm [seeing](https://codesandbox.io/embed/bvaughnreact-window-fixed-size-list-vertical-zoq5p).
2. The list isn't actually scrolling to element `#15`, I see that probably as a problem with my code, as I should perhaps scroll to it after `display: none` has been removed. An alternative to this would be to detect when `display: none` has been removed, but that's probably not worth the hassle.

**Comment by chinmay17** [comment]
@fabiospampinato Do you mean the bug here is that the List component should do nothing when `scrollToItem` is invoked if the list element has `display: none`? Could you please update the title of the issue accordingly?

**Comment by fabiospampinato** [comment]
The bugs here are that the list looks broken and it isn't scrolling to the right place. Maybe the second bug is not worth fixing though.

I've updated the title, I hope it's a bit more clear now.

**Comment by benkeen** [comment]
Apologies if this isn't precisely the same scenario as this ticket, but if not it's awfully close. I have 2 tabs, both containing a react-window list with a search field above it that filters both lists. When I scroll one list, switch to the other tab, do a search (which alters the results of both lists), then tab back, the scroll position isn't reset to zero. Because the search can return totally different number of results, the scroll position can be incorrect. 

After some digginf, the root cause seems to be browser behaviour, not a react-window bug per se. As soon as you hide a scrollable div, the scrollTop position resets to 0, as this fiddle illustrates: https://jsfiddle.net/gfv03td4/ (just scroll the panel, look at the scrollTop pos, hide it, then check again).

If you reset the scroll position to 0 when the element is hidden it has no effect. The browser automatically returns the scroll position to the last known position when it becomes visible (which is reasonable default UX, I think.

To work around it, we detect this scenario and manually reset the scroll position once the tab becomes visible again. Feels like a bit of a kludge, but I'm not sure how this could realistically be solved by react-window.

**Comment by hardnold** [comment]
I'm having a similar problem (not the exact same one, but still related to `display: none`). 

I have a toggle-Link which shows and hides a container with `display: none` and `display: block`. 

```
          <p className={classes.tip} onClick={ this.toggleTip }>
            Toogle Text
          </p>
          <div className={classes.tipToggle} style={this.state.toggleOpen ? { display : 'block' } : { visibility : 'hidden' }}>
            <ol style={{ paddingLeft : '15px' }}>
              <li>Item 1</li> 
              <li>Item 2</li>
              <li>Item 3</li>
            </ol>
          </div>
```

```
toggleTip = () => {
    this.setState({ toggleOpen : !this.state.toggleOpen })
  }
```

On the same page I have an Input which triggers a live search after each keystroke and therefor updates the state.

If the toggle is closed, the page keeps scrolling to the top after each keystroke. If the toggle is closed, the page doesn't scroll and the Input stays at the same position (latter is the expected and wanted behavior).
