### ISSUE TITLE
Feature: Enable select/focus by scroll (separate renderHeight & scrollHeight)

### ISSUE THREAD

**Issue by philholden** [bvaughn/react-window#137]
I would like to use a react-window to focus an item from in a list by scroll position (think of Androids select by scroll date picker). If I had a long list of items I could place a needle in the middle of the screen. Whichever item was under the red line would be treated as focused. I would also know where the needle fell within the item.

![image](https://user-images.githubusercontent.com/1674806/52897173-612c6e00-31c9-11e9-928f-dee731467d8e.png)

E.g. This could be used to drive a slide show from a list of slide previews on a mobile phone. If the needle fell half way through the 10th slide in a scrolling list. The 10th slide would be shown on the screen with half its bullet points revealed.

This would work well with react-window but there is an edge case. The top and bottom items are not focusable because they cannot fall in the center of the screen. To solve this we could add an empty `50vh` item to the top and bottom of our list. Now every item is focusable by scroll. But we have wasted half our screen space. Imagine Google search if the results started half way down the page (not good).

![image](https://user-images.githubusercontent.com/1674806/52897261-5c1bee80-31ca-11e9-8418-e9bd91a36914.png)

But what if we could separate height (`renderHeight`) from `scrollHeight` We could have an item whose `scrollHeight` was `50vh` but whose renderHeight was `0`. I.E. the scrollbar would move for `50vh`, yet the rendered content would remain static until `50vh` worth of scroll space had passed. If such an item were placed at the top of the list the user would scroll for half a page before the first visible item began to scroll. During this time the page scroll position can be use to drive the needle to move from the top to the middle of the page. This makes every item focusable. It feels seamless because the momentum of the page scroll is transferred to the needle (and vice versa).

In our slide show example we may have some slides we want to stand out when we scroll because we will be jumping back and forth in our presentation (or will need them in the Q & A). We set these slides to have a `scrollHeight` that is double their `renderHeight` now for every `2px` of scrollbar scroll the page only appears to move by `1px`. These slides standout to the presenter because when they are under needle the scroll speed halves also making it easier to stop on these slides.

## Non breaking API change

In order for select by scroll to be implemented outside `react-window` the concept of an independent `scrollSize` would need to be added to `react-window`.    

`itemSize` could optionally return an array:

```javascript
index => renderHeight // by default scrollHeight = renderHeight
index => [renderHeight, scrollHeight]
```

**Comment by bvaughn** [comment]
I appreciate the detailed explanation of the feature you're looking for. Thanks for taking the time to write it up thoroughly.

That being said, this feature sounds extremely edge case. (I've never seen a similar request on either react-window or react-virtualized repositories.) My typical stance is _not_ to implement features that would only be useful to a small percentage of users because (a) they increase the bundle size for all users and (b) they increase the maintenance burden for me— so it really needs to be a feature that will be useful enough to justify both of those downsides.

You could build most of what you're describing in user space with the existing API. The only thing I'm not sure about is the first and last items. Perhaps you could do something clever by providing your own `innerElementType` and overriding scroll offset or height. That or you could just fork the library.

Thanks for understanding, and good luck!
