### ISSUE TITLE
Janky/choppy scrolling performance in Safari

### ISSUE THREAD

**Issue by lambrospetrou** [bvaughn/react-window#146]
Hello Brian, I have been working with `react-window` for 1-2 weeks and it's been working nicely. 

Until I tried using it with Safari on Mac...

I know it's most probably not an issue or bug of the library but I wanted to see if you encountered this before and if there is any way to improve it, maybe by overriding some of the CSS transforms that it uses, in case they are not ideal for use in Safari.

I prepared a sandbox at https://codesandbox.io/s/ql0ojjj356 which is a very simple adaptation of the original example closer to my needs though.

The issue is that when you **slowly scroll** you can see flickering of the content, and the scroll is a bit choppy, especially when you put them side by side with Firefox; Chrome is on a different level of butter-smoothness entirely.

I tried to profile the issue and investigate the cause but could not really find something concrete.

Any hint or suggestion would be amazing.

Thanks again for a great library!

**Comment by bvaughn** [comment]
TBH I'm not sure of the differences in the scrolling mechanisms between Safari and other browsers, but it looks like Safari is blocking on the "scroll" event handlers– which is causing it to stutter rather than just show a bit of empty space in the direction you're scrolling (like Chrome and Firefox do).

Given that you want to improve script time anyway, you might want to consider memoizing items [as shown in the docs](https://react-window.now.sh/#/examples/list/memoized-list-items). This speeds things up a bit:
https://61k6n6ormn.codesandbox.io

Also keep in mind that Code Sandbox is running your code in DEV mode which is expected to be slower (sometimes significantly slower) than production mode. Running the example code in production mode helps perf a good bit more in Safari.

It also looks like you [aren't assigning a `key` to items](https://reactjs.org/docs/lists-and-keys.html#keys). Not a huge deal in this case I think, since React will use the index– and the items don't change in your demo. But that's something to keep in mind.

**Comment by lambrospetrou** [comment]
>Given that you want to improve script time anyway, you might want to consider memoizing items [as shown in the docs](https://react-window.now.sh/#/examples/list/memoized-list-items)
>...
>It also looks like you [aren't assigning a `key` to items](https://reactjs.org/docs/lists-and-keys.html#keys). Not a huge deal in this case I think, since React will use the index– and the items don't change in your demo.

This is my bad, I didn't make the codebox example complete, but in my project I do use memoization wherever possible and proper keys.

>Also keep in mind that Code Sandbox is running your code in DEV mode which is expected to be slower (sometimes significantly slower) than production mode. Running the example code in production mode helps perf a good bit more in Safari.

I admit that even though I thought about this, I didn't confirmed it, but with my actual project the choppy scrolling is still there compared to Chrome/FF, albeit less than the DEV mode.

I was hoping you hit this issue before and have a fancy hack or some override that triggers good performance in Safari :) 

One thing I noticed while profiling is that when setting `overscanCount > 20`, causing multiple rows to be rendered while scrolling, most of the time is spent destructing and removing the nodes from the DOM. And the main time-consumers were functions from React. I did some work-arounds, i.e. grouping rows together in order to just `remove` a single node instead of all the `overscanCount` nodes which helped a bit, but Safari was still behind.

Also, the other hack/workaround/feature I mentioned in [this issue](https://github.com/bvaughn/react-window/issues/111#issuecomment-460067279) helped a bit to avoid unmounting hundreds of nodes from the DOM while scrolling.

Anyway, this is definitely not a problem with the library so feel free to resolve this issue if you want.

**Comment by bvaughn** [comment]
Thanks for the extra information. I'm glad we had this exchange (so others can find it in the future) but I'm not sure of any silver bullets for Safari beyond what we've discussed.

If I think of anything new though I'll come back and update this issue.
