### ISSUE TITLE
Issues with scrollTo API on nested virtualized lists

### ISSUE THREAD

**Issue by ztanner** [bvaughn/react-window#149]
Hey! Thanks for such an awesome library - huge fan of your work on windowing, Brian. 

I might be testing the limits of the library here, but for some reason virtualizing a list inside of a list and having `scrollTo` events on both the outer and inner list, causes weird behavior.

Here's a codesandbox example. https://codesandbox.io/s/q86j59mo86

To reproduce, scroll a bit down the page (this will call scrollTo on the outer list). Then click one of the "scroll row" buttons. The behavior I've seen is strange - the row (or group of rows, depending on how far down you've scrolled) will disappear until you scroll again.

Having a hard time determining if this is user error or a potential bug. Thanks in advance!

**Comment by bvaughn** [comment]
Hey @ztanner.

`height: 100%` isn't supported for vertical scrolling lists. The list (and grid) component listens for "scroll" events within itself and updates its internal state based on the scroll values. You're trying to use it in more of a "controlled" mode– which isn't supported (and probably isn't something I want to support, because `WindowScroller` was kind of a pain to maintain on react-virtualized).

Any horizontal scrolling (not just clicking the "scroll to" button) breaks the demo.

I think you can make this work by blocking inner scroll events from bubbling up and resetting the outer scroll state:
https://codesandbox.io/s/o9ylj5ro69

...but it's not something I want to officially support (at least for now) so if it breaks, it breaks 😅 good luck!

**Comment by bvaughn** [comment]
> Hey! Thanks for such an awesome library - huge fan of your work on windowing, Brian.

P.S. Thanks!

**Comment by ztanner** [comment]
Thanks so much for the workaround - seems like a good stopgap solution for the time being. Totally get why you wouldn't want to support the API, I'm really happy with the surface area of react-window.

🍻

**Comment by bvaughn** [comment]
That's nice to hear 😄 thanks for being so understanding
