### ISSUE TITLE
What changed between 0.1.1 and 1.0.0-alpha.3?

### ISSUE THREAD

**Issue by kennetpostigo** [bvaughn/react-window#15]
Just asking because i'm curious about the difference between different implementations of virtualized lists and was pleasantly surprised to see react window being only `92b`, but then saw a more recent release (1.0.0-alpha.3) that shot it up to `5.3kb`:
https://bundlephobia.com/result?p=react-window@0.1.1

The other implementation I was looking at is sitting at `3.5kb`:
https://bundlephobia.com/result?p=react-tiny-virtual-list@2.1.4

**Comment by bvaughn** [comment]
The 0.1.1 release you reference was nothing. 92b is too small to be anything interesting. It was just a placeholder release from the person who used to hold this package name. You can see this for yourself:
https://unpkg.com/react-window@0.1.1/lib/

This lib has nothing to do with react-tiny-virtualized-list. So the size comparison isn't that meaningful.

This lib is structured to be smaller if you only use some of its components, so looking at the full size via bundle phobia isn't all that meaningful a stat.

Anyway, this is an alpha still too, so this is probably all a bit premature. :)

**Comment by bvaughn** [comment]
I also want to point out that the NPM package for react-window hasn't been minified or envified yet. This is intentional, because it has special DEV mode validation and warnings.

Like React itself, you'll want to minify+envify your app anyway, which will make react-window _much smaller_.

So don't read too much into bundle phobia size stats

**Comment by kennetpostigo** [comment]
@bvaughn yea that makes sense, I was just curious 😄. I was under the impression that bundlephobia set the env to production, and it does show the size when minified.

**Comment by bvaughn** [comment]
Sorry for the quick replies last night. I was on my mobile phone.

That's fair! Bundle Phobia is doing some minification to get to that number because the [raw CJS bundle in NPM is 62.51 kB](https://unpkg.com/react-window@1.0.0-alpha.3/dist/), and Bundle Phobia says that react-window@1.0.0-alpha.3 is [5.3kB "minified + gzipped"](https://bundlephobia.com/result?p=react-window@1.0.0-alpha.3).

But that number still seems a bit vague to me, because react-window has multiple components. So how is Bundle Phobia specifying which exports to use?

To test this myself, I made a new `create-react-app` build:
```
File sizes after gzip:

  36.94 KB  build/static/js/main.a0b7d8d3.js
  299 B     build/static/css/main.c17080f1.css
```

Then I installed react-window@alpha and plugged in `FixedSizeList`:
```
File sizes after gzip:

  41.52 KB (+4.58 KB)  build/static/js/main.2b4eba24.js
  299 B                build/static/css/main.c17080f1.css
```

So it looks like the added cost 4.58 KB (including the code I added to `App.js` to actually _use_ the list). But looking at the built bundle, I see it contains more than just the `FixedSizeList` component– it also contains  `VariableSizeList` _and_ both `FixedSizeGrid` and `VariableSizeGrid`– so this is still kind of a worst case scenario. So tree shaking isn't working correctly for the build.

By manually mucking around a bit to strip out the un-used list and grid implementations, we can shave another 2.25 KB off of the minified + gzipped size, bringing the new added size to 2.33 KB.
```
File sizes after gzip:

  39.27 KB (-2.25 KB)  build/static/js/main.4e15cf18.js
  299 B                build/static/css/main.c17080f1.css
```

I'm not sure how much of the tree-shaking issue will be improved by the upcoming react-scripts@next release (which updates to Webpack 4) and how much will require changes to the react-window bundle. If this is something you're knowledgable about, I'd love to have your help!

**Comment by kennetpostigo** [comment]
@bvaughn I'd be glad to help :)

**Comment by bvaughn** [comment]
Fantastic!

**Comment by kennetpostigo** [comment]
Do you think you can publish your CRA test project that you mentioned above? Want to use it to test a branch i'll work off of.

**Comment by bvaughn** [comment]
By the way! I just re-test this with the latest react-window release (1.0.2) and size increase after adding `FixedSizeList` is +2.26 KB [thanks to a few build optimizations](https://github.com/bvaughn/react-window/blob/master/CHANGELOG.md#102).
