### ISSUE TITLE
Is there any way to access scrollHeight and clientHeight?

### ISSUE THREAD

**Issue by despagito** [bvaughn/react-window#170]
I want to do something when user scroll the list to bottom, but my previous code is not working now👇

```js
this.messageList.current.scrollTop + this.messageList.current.clientHeight === this.messageList.current.scrollHeight
```
so is there any way to fix this, would be better if there's a direct API.

**Comment by bvaughn** [comment]
> Is there any way to access scrollHeight and clientHeight?

Did you check out [the documentation](https://react-window.now.sh/#/api/FixedSizeList)? Looks like the `onItemsRendered` prop should be sufficient for determining when you've reached the bottom of the list.

Otherwise, both `innerRef` and `outerRef` props are available to give you access to the scroll dimensions.
