### ISSUE TITLE
Class component in <VariableSizeList>

### ISSUE THREAD

**Issue by kalpeshsingh** [bvaughn/react-window#177]
I have a class component and want to use `react-window` on that. Is there any way I can use it without converting it to functional component or pure component?

I have read docs and couldn't find anything mentioned about class component. Happy to contribute to documentation once I know any method to use with class component or at least we can mention about class component support.

**My code:** 

```
import { VariableSizeList as List } from 'react-window';
import HeavyClassComponent from './Heavy/Component';

<List height={15} itemCount={1000} itemSize={() => 20} width={30}>
    <HeavyClassComponent>
</List>
```

**Error:** 
```
Invariant Violation: Element type is invalid: expected a string 
(for built-in components) or a class/function (for composite components) but got: object
```

**Comment by bvaughn** [comment]
You can use a class component as an item renderer in the same way as a function component. The trouble isn't that it's a class component, but that you're converting it to a React element (`<HeavyClassComponent/>`) rather than just passing the component type directly (`HeavyClassComponent`) like the docs show.
