### ISSUE TITLE
Scroll to item unexpected behavior

### ISSUE THREAD

**Issue by BnayaZil** [bvaughn/react-window#178]
As it is presented in the [documentation](https://react-window.now.sh/#/examples/list/scroll-to-item) clicking on the button scrolls down so item No. 200 is displayed, now the unexpected behavior is that I would expect the item No. 200 to display as first over as last.

Current behavior
![image](https://user-images.githubusercontent.com/13505136/54394522-c171db00-46b5-11e9-8bfa-4a888c1ad468.png)

Expected behavior
![image](https://user-images.githubusercontent.com/13505136/54394586-f8e08780-46b5-11e9-80d7-6438393c5f3b.png)

**Comment by BnayaZil** [comment]
Sorry, I missed the `align` property.

**Comment by bvaughn** [comment]
As [the docs say](https://react-window.now.sh/#/api/FixedSizeList):
![Screen Shot 2019-03-14 at 3 16 50 PM](https://user-images.githubusercontent.com/29597/54395153-3a4c4500-466c-11e9-9639-d8e6679518f1.png)

List scrolls only enough so that the item is fully visible. If you've scrolled past it, it will scroll back just enough so the item is at the top. If you haven't scrolled far enough, it will scroll just enoughs ot hat the item is at the bottom.
