### ISSUE TITLE
Changing props of one item will update the whole list

### ISSUE THREAD

**Issue by ffjanhoeck** [bvaughn/react-window#186]
Hey,

I saw your memoized example and I saw that the whole List gets updated if a state of an item gets changed. See the Gif below. This is your example from https://react-window.now.sh/#/examples/list/memoized-list-items

![2019-03-18_13-43-16](https://user-images.githubusercontent.com/9037364/54530875-45f97d80-4984-11e9-921b-ba8554feb154.gif)

Currently I have the same problem with my list. I have an checkbox in every ListItem and if a user checks this checkbox, then every item will be unmounted and clearly new mounted. Thats a big problem, because its really slow.

![image](https://user-images.githubusercontent.com/9037364/54531005-91139080-4984-11e9-979e-6afde8861fc9.png)

Hopefully anyone can help me :)

**Comment by BertelBB** [comment]
I have the exact same use case and problem, and have not been able to find a solution...

**Comment by bvaughn** [comment]
That's because changing an item [creates a new `items` array](https://github.com/bvaughn/react-window/blob/53c26b429d5f4d9bba540df8f70810afc8a34e18/website/src/routes/examples/MemoizedListItemsExample.js#L51-L60) which [creates a new `itemData` object](https://github.com/bvaughn/react-window/blob/53c26b429d5f4d9bba540df8f70810afc8a34e18/website/src/routes/examples/MemoizedListItemsExample.js#L94-L97). It's important that memoization techniques are invalidated then their data changes.

If you want the items to be more robust to this sort of change, you could implement your own [`areEqual`](https://reactjs.org/docs/react-api.html#reactmemo) function (or [`shouldComponentUpdate`](https://reactjs.org/docs/react-component.html#shouldcomponentupdate)).

The demo's purpose is just to show how `itemData` and memoization can work together to pass complex values.

**Comment by ffjanhoeck** [comment]
I had testest it with my own shouldComponentUpdate function but this function won't be executed, if the component will gets umounted again and again

**Comment by bvaughn** [comment]
> if the component will gets umounted again and again

There's no way to memoize a component that gets unmounted again. That's not what happens in my demo though. If it's what happens in your app, there's something else going on– and I can't speculate about what.

**Comment by ffjanhoeck** [comment]
@BertelBB Did you find a solution?

**Comment by BertelBB** [comment]
@ffjanhoeck Not really, no. I realised that my use case is actually a little bit different in the sense that my list can also be sorted/filtered. What I did is I pass in the **itemData** and **itemKey** props so that I manually set the key prop for every item. The whole list still updates but it is not as laggy as before.
https://react-window.now.sh/#/api/FixedSizeList here you can read about the props I am referring.

**Comment by ffjanhoeck** [comment]
@BertelBB I already implemented that function yesterday, thank you :)
But the problem is not fixed :(
Here is an GIF what is laggy - as you can see is took some milliseconds to check an item.
Everything is memoized or have a implemented shouldComponentUpdate.

![2019-03-20_15-09-49](https://user-images.githubusercontent.com/9037364/54690785-6cedb600-4b22-11e9-81b2-39e0a07b351c.gif)

**Comment by BertelBB** [comment]
@ffjanhoeck Yes, have the same issue. I unfortunately do not have time to look further into this as of now. But I will let you know if I find a better solution :)

**Comment by bvaughn** [comment]
@ffjanhoeck Any chance I could take a look at the app you showed in the GIF above? I'd be curious to run a profiler and see where the slowness is coming from.

**Comment by ffjanhoeck** [comment]
@bvaughn Yes sure -  I have send you the credentials on your email! :)

I think the slowness comes from the short preview of an item (The picture and the blue text with the secondary text represents the EntityShortPreview Component). But it is not a problem for one item. The problem is that all items get unmounted and mounted on select and if you sum up this, then it is slow.

Thats my current feeling :D But maybe you can find some other issues :)

**Comment by ffjanhoeck** [comment]
This happens if a user select one item (on my development app)

![image](https://user-images.githubusercontent.com/9037364/54735517-f5ae3580-4ba6-11e9-9dca-b2f77742e24b.png)

**Comment by AndreaZChen** [comment]
@ffjanhoeck I ran into the exact same issue, and after some investigation, I managed to figure out the cause: it's because we're using **anonymous functions** as item renderers, instead of named components. I'm no React guru, but I believe this messes up React's reconciliation, since the components aren't recognizably the same between renders.

I made a CodeSandbox example illustrating the problem here: https://codesandbox.io/s/qx4088mn36

**Comment by bvaughn** [comment]
That's what I'm seeing too after a quick look this morning. (Was writing an email but got interrupted.) Moving the inline function to an instance prop sped things up, (but also broke a few other things that I didn't have  time to track down due to the size of the repro case).

> I believe this messes up React's reconciliation, since the components aren't recognizably the same between renders.

This is correct. 👍

**Comment by AndreaZChen** [comment]
Hmm. This is unfortunate, because I'm writing my project using ReasonReact, which (currently) lacks the necessary props spreading/functional component features to avoid this problem. I recognize that this is not in any way a problem with react-window, just a limitation of ReasonML's type system, but I suppose it's worth mentioning in case anybody else stumbles upon this thread.

**Comment by bvaughn** [comment]
To be clear, this is why all of the docs examples show the  item render being defined outside of the parent component, and the [memoization example](https://react-window.now.sh/#/examples/list/memoized-list-items) shows how to share data between the two. (Basically it's like a lighter weight, built-in context.)

**Comment by ffjanhoeck** [comment]
Great, I will take a look! :)

**Comment by suitux** [comment]
> To be clear, this is why all of the docs examples show the item render being defined outside of the parent component, and the [memoization example](https://react-window.now.sh/#/examples/list/memoized-list-items) shows how to share data between the two. (Basically it's like a lighter weight, built-in context.)

Thanks!!!
