### ISSUE TITLE
When dragging the scroll bar on a variable sized grid, the bar moves ahead of the mouse

### ISSUE THREAD

**Issue by joespeargresham** [bvaughn/react-window#191]
When you click and drag the scroll bar down on a variable sized grid the thumb bar moves quicker than the cursor.

This only happens the first time that you scroll down. It subsequently corrects itself.

It appears to be more noticeable on a grid with a larger amount of rows, but I can replicate it on the demo here https://react-window.now.sh/#/examples/grid/variable-size

Seems to work fine on a fixed sized grid.

**Comment by bvaughn** [comment]
This is expected, since variable size list/grid use _estimated_ item sizes initially and refine them as items are measured. When there's a delta between the _estimated_ and _actual_ size, the available scroll size is adjusted by that amount- which can impact the scroll thumb slightly. Usually this isn't very noticeable, since it's done gradually (as items are measured).

It's not really something that can be avoidable. It can be minimized by specifying an accurate `estimatedItemSize` for list (or similar props for grid).

The alternative would be to eagerly query all item heights but that can have negative performance impacts and much of the strategy of a library like this is to delay and/or amortize expensive CPU operations.
