### ISSUE TITLE
scrollTo method does not report isScrolling

### ISSUE THREAD

**Issue by leahaense** [bvaughn/react-window#195]
Hi,

we use a `FixedSizeList` inside a `WindowScroll` component that triggers the `scrollTo` method on the list component. Our items are quite heavy to render and thus if you scroll very fast you'd often get empty space. I wanted to use the `useIsScrolling` feature, but noticed that this is never reporting `isScrolling` as `true`. 
I checked the code and noticed that this is deliberate since there are tests that check explicitly that. Why is that? Or is there another way to achieve having a window scrollbar instead of just one for the list?

**Comment by bvaughn** [comment]
It is deliberate, yes. I'll try to explain my reasoning.

"scroll" events happen quickly, and can be hard for JavaScript to keep up with. If JavaScript doesn't keep up, then scroll jank happens. With windowed libs like react-window, this means checkerboarding (empty space). In non-windowed libs, it means the browser stops responding to the user's house/keyboard. Either way, we want to minimize this.

The `isScrolling` exists as one way to help minimize. It lets you know that item you're about to render is being shown while the user is scrolling. This has significance in two ways:
1. It needs to be rendered very fast. So if your item is "heavy", you wouldn't want to render the whole thing in this case.
2. It might not  even be visible for long (because the user might just keep scrolling right past it).

The `scrollTo` method is different. It isn't called  many times in a row (_under normal circumstances_) and so if it passed `isScrolling: true` then it would just leave the list rendered in a strange state. In your case, it sounds like you _are_ calling this method many times- but in a way that isn't really supported by the library. (I don't know what `WindowScroller` component you're using or how you've made it work. Would be curious to see though, but that's a side issue.)

I haven't really thought about this much, but initially... here are two ideas you might want to try.  (I'm not sure how good either would be for performance. You'd  need to check.):
1. Use the `outerRef` prop to just manually scroll the div element, and let lists's "scroll" event handler take over from there.
1. Consider using the context API to expose your own `isScrolling` param to item renderers for the case of `scrollTo`.

If neither of those options seem appealing, I would also be willing to look at and consider a PR that adds a second param to `scrollTo` that is a boolean for whether or not it should set `isScrolling` to true temporarily. I think this would be very easy to add, although it would also require test and documentation updates. I'd want to think a little bit more about this before committing to merging the change though, because I don't think it's a common use case.

I don't plan on taking any action on this item myself, so I'm going to close it. We can still talk on the issue though.

**Comment by leahaense** [comment]
Thank you very much for your detailed answer. I already tried your first suggestion, but since we use the `WindowScroller` together with an `AutoSizer`, `outerRef` is as big as the whole list would be and thus can not be scrolled on a DOM level (`WindowScroller` and `AutoSizer` were implemented by us inspired by the components in `react-virtualized`. See at the end of the post for the implementation).
I will give the context API a try, this seems to me the only way I could make this fully work on our end. 
I will also discuss this further with my colleague, I'm sure we come up with some solution :).

Thanks again!

```
interface ScrollPosition {
	scrollTop: number;
	scrollLeft: number;
}

interface WindowScrollProps {
	children: (p: { width: number; height: number } & ScrollPosition) => React.ReactNode;
	onScroll?: (p: ScrollPosition) => void;
}

export function WindowScroll({ children, onScroll }: WindowScrollProps) {
	const scrollElementPosition = useScrollPosition(window, onScroll);
	const scrollElementDimension = useDimension(window);

	const container = window.document.documentElement.getBoundingClientRect();
	const thisElement = ReactDOM.findDOMNode(this) as Element;
	const thisElementRect = thisElement ? thisElement.getBoundingClientRect() : { top: 0, left: 0 };
	const offset = { top: thisElementRect.top - container.top, left: thisElementRect.left - container.left };

	return (
		<>
			{children({
				width: scrollElementDimension.width,
				height: scrollElementDimension.height,
				scrollTop: Math.max(0, scrollElementPosition.scrollTop - offset.top),
				scrollLeft: Math.max(0, scrollElementPosition.scrollLeft - offset.left)
			})}
		</>
	);
}

interface AutoSizerProps {
	children: (
		p: {
			width: number;
			height: number;
		}
	) => React.ReactNode;
}

export function AutoSizer({ children }: AutoSizerProps) {
	return (
		<Measure offset>
			{({
				measureRef,
				contentRect: {
					offset: { width = 0, height = 0 }
				}
			}) => <div ref={measureRef}>{children({ width: width, height })}</div>}
		</Measure>
	);
}
```
