### ISSUE TITLE
[Question] React Native support?

### ISSUE THREAD

**Issue by Steffi3rd** [bvaughn/react-window#235]
Hello @bvaughn, thanks for this amazing package! 

I would like to know if this New `react-virtualized` support `react-native`?

**Comment by bvaughn** [comment]
Nope! :) RN has its own virtual list options bundled with the framework

**Comment by mperezguendulain** [comment]
Hi @Steffi3rd, just for said you that RN has some similar to react-window components, that is 'flatlist' or 'virtualizedlist', but don’t have implemented the windowing technique, i. e, render all items (you can review this, inspecting the DOM of your RN app), this results in a not very good performance.
Imagine this: You have a table, this table, has a lot of rows (1000), if you use flatlits o virtualizedlist components, the change takes a lot of time in showing, because apply the change over the 1000 rows. Is for this reason that I recommend using the windowing technique because using this technique the change is applied only over the data that you can see (example 15 rows).
I was looking a component that implements this technique, and I didn't find any, but I found a library, that works a little different, but has a good performance, you can read more about how it works in the GitHub page: https://github.com/Flipkart/recyclerlistview
¡Greetings!

**Comment by bvaughn** [comment]
RN components like [`FlatList](https://facebook.github.io/react-native/docs/flatlist.html) and [`SectionList`](https://facebook.github.io/react-native/docs/sectionlist) are windowed. Both of those components are wrappers around [`VirtualizedList`](https://facebook.github.io/react-native/docs/virtualizedlist).

From the docs:
> Virtualization massively improves memory consumption and performance of large lists by maintaining a finite render window of active items and replacing all items outside of the render window with appropriately sized blank space. The window adapts to scrolling behavior, and items are rendered incrementally with low-pri (after any running interactions) if they are far from the visible area, or with hi-pri otherwise to minimize the potential of seeing blank space.

**Comment by mperezguendulain** [comment]
Yes, I had already read this, but still, I did my tests, and render me all the elements, I was looking at the issues reported in the RN repo and found this:
https://github.com/facebook/react-native/issues/18142#issuecomment-437603136

I took the test mentioned in that commentary and I found that the Virtualizedlist render each item.

**Comment by bvaughn** [comment]
Ah. Sounds like a bug if so then. :(

**Comment by mperezguendulain** [comment]
Yeah, I think so. I hope they fix it soon. The bad news is they've already closed the issue :(

**Comment by bvaughn** [comment]
I can help there, at least.

**Comment by mperezguendulain** [comment]
Yeah, ¡that'd be great! 👍

**Comment by nandorojo** [comment]
Has anyone made a solution that uses React window on web and FlatList on native?

I would like a solution like that which uses something like a `.web.tsx` and keeps a consistent API for web and mobile.
