### ISSUE TITLE
Ok to put callbacks in the data source?

### ISSUE THREAD

**Issue by abhikp** [bvaughn/react-window#238]
I'm trying to build an interactive grid with `react-window` and am new to the library. I was thinking of using the `itemData` prop as a way to pass callbacks that change state of the grid data.

For instance, I'm trying to highlight a row on hover and use `itemData` to pass the highlighted row (`highlightedRow`) and the set state action (`setHighlightedRow`) to change the index of the highlighted row: https://codesandbox.io/s/j437y95ljw

Is this the appropriate way to do something like this?

**Comment by bvaughn** [comment]
In general, passing callbacks is fine. The way the Code Sandbox you linked to does it will break memoization though, since the `itemData` object (wrapper) will be recreated every time the `Example` component is rendered.

If the `highlightedRow` value changes, you'd expect this- but what if a parent causes a re-render that wouldn't otherwise require cells to re-render?

You can confirm this using the [React DevTools profiler](https://reactjs.org/blog/2018/09/10/introducing-the-react-profiler.html). For example, [here](https://codesandbox.io/s/n7n979p67j) is a sandbox that builds on top of yours to add an increment button. Each time that button is clicked, your `Example` component is re-rendered. Even though the contents of your grid don't change, every cell is re-rendered because of the object wrapper:
<img width="796" alt="Screen Shot 2019-05-07 at 5 34 54 PM" src="https://user-images.githubusercontent.com/29597/57341257-7d67e900-70ee-11e9-9ea9-a6f5d395010a.png">

Maybe this is okay, but if your cells are expensive to render, it could also be a performance problem. Check out the docs. They show how to memoize that object wrapper to avoid this:
https://react-window.now.sh/#/examples/list/memoized-list-items

Here's an updated Code Sandbox: https://codesandbox.io/s/9jkz2oollo

You can use the Profiler to confirm that it doesn't re-render cells when you click the "increment" button:
<img width="796" alt="Screen Shot 2019-05-07 at 5 34 49 PM" src="https://user-images.githubusercontent.com/29597/57341246-76d97180-70ee-11e9-8df1-d92a40c75de0.png">

We can see that even in this tiny example, memoization saves a significant amount of time. (Admittedly this example is also running in development mode, which is expected to be slower. Still...)

**Comment by abhikp** [comment]
Thanks for the tips and sorry for the missing question label!

**Comment by bvaughn** [comment]
No worries on that. Only maintainers can add labels! 😉
