### ISSUE TITLE
Documentation/VariableSizeList: example of using `estimatedItemSize` with `itemSize`

### ISSUE THREAD

**Issue by chadoh** [bvaughn/react-window#263]
Seeing an example of how to use these together would be really helpful.

Also, I get an error for invalid values of `itemSize`, but `estimatedItemSize` threw no error when I mistakenly passed a function to it. 

Some specific questions I have:

* When does `itemSize` get called? 
* Does it override `estimatedItemSize` at that time?
* Do I have access to the _rendered_ item in the `itemSize` function, so I can adjust its height to the elements "natural" height, without reverse engineering the browser's height calculation?

**Comment by bvaughn** [comment]
> Seeing an example of how to use these together would be really helpful.

Just add an `estimatedItemSize` prop to the `VariableSizeList` docs example:
https://react-window.now.sh/#/examples/list/variable-size

There isn't anything special about it really. 😄 It just makes the initial size estimate slightly more accurate, which means it will change  less over time as actual measurements are requested.

> Also, I get an error for invalid values of `itemSize`, but `estimatedItemSize` threw no error when I mistakenly passed a function to it.

I'd prefer to  avoid multi-part GitHub issues. I don't really consider this a RW bug though. `estimatedItemSize` is explicitly marked as a **number** type in the docs. 😄

> When does itemSize get called?

Whenever react-window needs to know about the _actual_ size in order to determine what slice of  data to render.

> Does it override estimatedItemSize at that time?

It doesn't "override"`estimatedItemSize` so much as it refines the total (estimated) scrollable size with more accurate (actual) information. 

> Do I have access to the rendered item in the itemSize function

No. There is no rendered item yet.

**Comment by chadoh** [comment]
> Just add an estimatedItemSize prop to the VariableSizeList docs example

Can you link me to the spot in the code where I would update this, instead of the live example?

> I don't really consider this a RW bug though. `estimatedItemSize` is explicitly marked as a `number` type in the docs. 😄

But if I miss that, then my browser console doesn't help me in the same way it helps me if I mess up the `itemSize` prop. 

> I'd prefer to avoid multi-part GitHub issues.

Sure, but this is all about documenting these two props, in one way or another.

> There is no rendered item yet.

How can I adjust the item's height to the element's "natural" height, without reverse engineering the browser's height calculation? I have a list of card-style elements, with an unknown content length that could flow to multiple lines depending on browser screen width. If I understand this `itemSize` function correctly, I need to do something like calculate the container width, calculate text size, make a guess at how many lines the text will wrap to, and set the item height accordingly. This is what I refer to as "reverse engineering the browser's height calculation", and it seems unacceptably brittle. Is there some way around this, other than convincing the design department to update styles to truncate content on narrow screens?
