### ISSUE TITLE
Wrapping a Semantic UI List 

### ISSUE THREAD

**Issue by jjarrett21** [bvaughn/react-window#277]
I've got an established List component I've built with semantic and I'd like to wrap it in window but I can't seem to get it sorted? Can Anyone point me in the right direction? 

`<AutoSizer>
              {({ height, width }) => (
                <FixedList height={height} width={width} itemCount={count} itemSize={45}>
                  {<List divided>{sourcesList}</List>}
                </FixedList>
              )}
            </AutoSizer>`

**Comment by jjarrett21** [comment]
Update: ` <List divided>
              <AutoSizer>
                {({ height, width }) => (
                  <FixedList height={height} width={width} itemCount={count} itemSize={45}>
                    {sourcesList}
                  </FixedList>
                )}
              </AutoSizer>
            </List>`

This bit compiles and renders without issue but the list does not show up.

**Comment by bvaughn** [comment]
I think this is probably more of a Stack Overflow question than a GitHub issue. I'd suggest sharing a runnable Code Sandbox example too, so people can take a look quickly rather than having to recreate your entire setup to try a suggestion. Feel free to link the Stack Overflow question here on this issue and I'll take a look if I get a chance. Going to close this for now though :)
