### ISSUE TITLE
How can I render multiple components

### ISSUE THREAD

**Issue by ShivamJoker** [bvaughn/react-window#292]
Please provide an example of utilizing the map function and how can we render dynamis contents fetched from an API or anywhere

This is my code i want to implement react window
```
const RenderDatabase = ({ songs }) => {

  const { setCurrentVideoSnippet } = useContext(GlobalContext);

  const handleClick = song => {
    // set all the info of current clicked video in this object
    setCurrentVideoSnippet({
      id: song.videoId,
      audio: song.audio,
      title: song.title,
      channelTitle: song.channelTitle,
      maxThumbnail: `https://img.youtube.com/vi/${
        song.videoId
      }/maxresdefault.jpg`,
      sdThumbnail: `https://img.youtube.com/vi/${song.videoId}/sddefault.jpg`
      // this is the url of the max resolution of thumbnail
    });
  };


  const renderResult = songs.map(song => {
    return (
      <div key={song.videoId}>
        <ListItem
          alignItems="flex-start"
          button
          onClick={() => handleClick(song)}
        >
          <ListItemAvatar>
            <Avatar
              className="searchThumb"
              style={{ width: "60px", height: "60px", marginRight: "15px" }}
              alt={song.title}
              src={`https://img.youtube.com/vi/${song.videoId}/maxresdefault.jpg`}
            />
          </ListItemAvatar>
          <ListItemText
            primary={song.title}
            secondary={
              <React.Fragment>
                <Typography
                  component="span"
                  variant="body2"
                  color="textPrimary"
                >
                  {song.channelTitle}
                </Typography>
              </React.Fragment>
            }
          />
        </ListItem>
    <Divider />
      </div>
    );
  });

  return (
    <List>
    {renderResult}
    </List>
  );

};
```

**Comment by bvaughn** [comment]
That is not how react-window works.

Fork one of the many examples from the documentation and show me what you've tried first. I will take a look and offer suggestions, but it doesn't look like you've even read the docs based on this example you provided
L.

**Comment by ShivamJoker** [comment]
I have seen all the examples and read it 
And i tried putting multiple divs in the return props it doesnt work so
I think the ideal solution would be to get the total length of the array and utilize the index value to fetch data from all of them right ?

**Comment by bvaughn** [comment]
This bit of your snippet made me think you hadn't read the docs:
```js
<List>
  {renderResult}
</List>
```
Since `List` requires several props, all missing.

Start by forking this example:
https://codesandbox.io/s/github/bvaughn/react-window/tree/master/website/sandboxes/fixed-size-list-vertical

What would you do if you didn't know the `itemCount` value? You would probably use `songs.length` right?

But you don't want to recreate your item renderer (your `renderResult` component) each time you render, because that will cause React to recreate those instances rather than update them. So the next step I would suggest would be to look into using the `itemData` prop as shown on this page/example:
https://react-window.now.sh/#/examples/list/memoized-list-items
