### ISSUE TITLE
Vertical Scroll for a long width row FixedSizeList

### ISSUE THREAD

**Issue by faizaankhan** [bvaughn/react-window#294]
Hello, 
I am using FixedSizeList for rendering very large data, thanks to react-window that everything has been a smooth process with smoother output.

For a couple of days, I am trying to add a vertical scroll bar using react-custom-scrollbars, and I could easily integrate it and make it usable. BUT the issue for which I have spent a couple of days and finally I am here is putting the Vertical Scrollbar at the end of the browser page, like a sticky element, so that the user doesn't need to scroll horizontally till the end of the list and then scroll vertically.

I know using grid was an option here, but due to some situations, we had chosen to use FixedSizeList. The width of each row is going up to 3-4 page scrolls.

How can I make this sticky vertical scroll bar?

**Comment by bvaughn** [comment]
This type of question is probably best asked on Stack Overflow (or somewhere similar).

I don't use custom scroll bars myself. Never had a requirement to. I don't know how you'd accomplish what you're asking, or I'd offer suggestions.

Since I don't know though, and I don't plan on spending time to research it (sorry pretty busy these days) I'm going to close this. Hope you understand.
