### ISSUE TITLE
Items with long labels wrap over next items

### ISSUE THREAD

**Issue by Ptival** [bvaughn/react-window#342]
When an item's label length exceeds the width of the list, the text wraps around, but instead of pushing the next items down, it overlaps:

<img width="306" alt="image" src="https://user-images.githubusercontent.com/478606/66072694-60530d00-e50a-11e9-93f9-eaac01ac43ef.png">

Is there a solution to this?

**Comment by bvaughn** [comment]
CSS:
```css
white-space: nowrap;
text-overflow: ellipsis;
overflow-x: hidden;
```

**Comment by WesCook** [comment]
That fixes the display issue but now items on mobile will be truncated very early.

**Comment by Metwesh** [comment]
Helo Vaughn, 
I love this library and all the work you've done to maintain in this far :).
Anyways, I don't know why but when I add overflow hidden to the list item and scroll, I reach the end of my scroll when it clearly hasn't.

Like so
![ezgif com-video-to-gif](https://github.com/bvaughn/react-window/assets/94052626/6a4f6465-c590-4bf3-a530-81f6b015d45a)
See how it behaves as if it reached the end of the scroll area? instead of rendering white space?

Kindly note that this behavior only appears when adding overflow hidden to the list items.
