### ISSUE TITLE
[VariableSizeList] How can I resize item after changing its height?

### ISSUE THREAD

**Issue by cosloli** [bvaughn/react-window#344]
I'm using VariableSizeList to render a long form, each form item is expandable. So I want to resize the item height after expand it. But the `getItemSize` method is called only once. How can I recall `getItemSize` after it has been called?

**Comment by bvaughn** [comment]
Check out [the `VariableSizeList` docs](https://react-window.now.sh/#/api/VariableSizeList)? Specifically look at the `resetAfterIndex` method:

> **`resetAfterIndex(index: number, shouldForceUpdate: boolean = true): void`**
> VariableSizeList caches offsets and measurements for each index for performance purposes. This method clears that cached data for all items after (and including) the specified index. It should be called whenever a item's size changes. (Note that this is not a typical occurrance.)
>
> By default the list will automatically re-render after the index is reset. If you would like to delay this re-render until e.g. a state update has completed in the parent component, specify a value offalsefor the second, optional parameter.

**Comment by hendradevstack** [comment]
is possible use `async` for `itemSize`? 
Let say I have 100 images, all just url images, I have to request meta image (width, height) so when call `getItemSize` I use `async` request meta.
So the idea is when `getItemSize`, it will request first the meta, then return the metas and cache it. so I don't want request 100 meta once because the performance and time.

**Comment by sbeka** [comment]
Thank you! I solved my problem. If you are interested you can see)

https://github.com/sbeka/react-height-after-the-render/blob/master/src/App.tsx
