### ISSUE TITLE
onScroll called when <FixedSizeList /> is first rendered

### ISSUE THREAD

**Issue by jmcrthrs** [bvaughn/react-window#376]
I am attempting to maintain the scroll position of a <FixedSizeList /> when the user returns to the route containing the <FixedSizeList />.

1. User visits route with FixedSizeList
2. FixedSizeList renders
3. User scrolls until scrollTop=5000
4. Use FixedSizeList onScroll() to save scrollTop value in memory (not React state or Redux etc.)
5. Users navigates to a different route
6. Users returns to route with <FixedSizeList />
7. FixedSizeList renders
8. Use FixedSizeList scrollTo() in a useEffect() to scroll to the previous position (5000)

Unfortunately onScroll is called when [FixedSizeList mounts](https://github.com/bvaughn/react-window/blob/master/src/createListComponent.js#L245), which results in the scrollTop value in memory always overwriting the existing value with 0. 

This appears to be different than a conventional overflowing container with an onscroll() handler. e.g. a <div /> with overflowing content

I have re-created a demo of the issue here:
https://codesandbox.io/s/react-window-onscroll-called-when-component-first-rendered-s6zk5

I just realised when writing this that if I wrap the code in onScroll in a setTimeout(), the useEffect code runs first, and this essentially fixes the issue.

**Comment by bvaughn** [comment]
> Unfortunately onScroll is called when FixedSizeList mounts

This is kind of by design. This prop is called each time scroll position changes (including when it changes from `undefined` to 0).

Your application code could always ignore the initial callback using a ref (or similar tactic).

Updated sandbox at:
https://codesandbox.io/s/react-window-onscroll-called-when-component-first-rendered-jzij7

If you feel strongly that the current behavior is wrong though, I would review a PR to change it (assuming tests pass and everything). Otherwise, hopefully this will unblock you!

**Comment by jmcrthrs** [comment]
Yeah, I had the mounted idea before, but wasn't sure how to implement it. Thanks for the ref example. I think this is much clearer what is happening than my setTimeout solution.

**Comment by bvaughn** [comment]
No problem.
