### ISSUE TITLE
List with width defined by childrens

### ISSUE THREAD

**Issue by joan-saum** [bvaughn/react-window#378]
Hi there!

First of all, thanks for this library, it has really good performances!
I'm trying to use it in a way I'm not sure it is possible (I'm not able to make it works for now)

I want display a list of text as a Dropdown.
I made a small example in codepen you can see here : https://codesandbox.io/s/bvaughnreact-window-fixed-size-list-vertical-13qgn

My problem here is I don't want define the width of the List. I want the width of my list is defined by the width of my items inside. If an item has long text, the width of the list is big enough to display it on one line.
I tried use the AutoSizer but my parent has no width, no height and is in absolute position so the result is 0px 0px.

Is there a way to do it ?

Thanks in advance!

**Comment by bvaughn** [comment]
What you're describing is not a use case this library supports.

I don't think it would make sense to try to support this either, as a tight-fit width would require measuring all items (to find the largest one) which would defeat the purpose of windowing the data to begin with. Does this make sense?

I'm going to close this issue because I don't intend to take any action on it. Thanks!
