### ISSUE TITLE
FixSizeList not calling method Row when checkbox state changes

### ISSUE THREAD

**Issue by dkunzman77** [bvaughn/react-window#379]
Hi -

I have a list of one item with inner elements that are Material UI checkboxes.  When the checkbox's state changes the Row method is not being called.  This only happens when there is one element in the row.  I assume this is because of the shallow differ.  Any ideas?

Doug

**Comment by bvaughn** [comment]
This question is essentially asking the same thing as #357 and a few others.

List will not re-render you `Row` if none of the props have changed. You could enable a re-render by passing a new `itemData` value (or some other prop) so that React doesn't bail out when deciding whether it should re-render the list (and its row children).

**Comment by dkunzman77** [comment]
I added a key prop and that fixed   Would you consider a pull request of additional documentation?

**Comment by bvaughn** [comment]
Depending on the changes, sure. I'd at least consider it! :)

**Comment by dkunzman77** [comment]
Brain -

Hope you are having a good weekend.
I created a pull request with a more information for developers for React
Window.  Like me know what you think?

Doug
