### ISSUE TITLE
Wrong re-rendering after `scrollTo` action

### ISSUE THREAD

**Issue by artakpoghosyan1** [bvaughn/react-window#381]
When using `scrollTo` instead of `scrollToItem`  (e.g. when scrolling to last item), the list disappears and only a couple of items stay visible.

To reproduce the issue please click on **Scroll to last Item** button twice in the following example.

[Example](https://codesandbox.io/s/ancient-thunder-kdmsi?fontsize=14&hidenavigation=1&theme=dark)

**Comment by Mikoz93** [comment]
Is there any update on this? This is especially painful when using a custom innerElementType with table headers included, where scrollToItem doesn't really work as the offset isn't being calculated properly.

**Comment by Ganpatkakar** [comment]
I know its very late, I just joined the party now. Here is what you can do to avoid this wrong experience.

Looks like the issue is with the with usage not with the code implementation,

Try this convert your function like this

`scrollToLastItem = () => {
    this.listRef.current.scrollTo(10 * 35 - ScrollAreaHeight);
  };`
  
  Also scrollTo doesn't expect second param.
  
  So you need to scroll only till last top element.
  
The way I understood this library is, when you want to go to any position it will try to get that item at top of your container and then include 2 extra items on top and 2 extra items on bottom (condition of not including these when it reaches at bottom, same applied for top items when it reached at top).
 Now when you want to go to at very bottom then it will try to fetch that position item and -2 (from that index) at top and since it reaches at bottom so it wont add +2 (from that index) at bottom.
 
 Now in order to support this use above function to support it.
