### ISSUE TITLE
Adding new rows on the fly

### ISSUE THREAD

**Issue by airimia1995** [bvaughn/react-window#387]
Hi there!

First of all, great project!

Are there any plans to be able to append rows on the fly? I'll give you a use case.

We have a page where we view a table of events. When the web socket client receives a new event, we'd like to add it to the collection. If the user has rendered all the rows (i.e. they can see the last event) then any new events are appended and appear in view. If the user is not at the end of the collection, then the event is appended to the collection but it won't appear in the view.

Thanks!

**Comment by bvaughn** [comment]
You can implement the behavior you're describing already, using the existing API! :smile:

You would just need to increase the `itemCount` value you're passing as a prop, and optionally if you wanted to scroll the new things into view- use a method like `scrollToItem()`

Going to close this issue since there's no action required on my end. :smile:
