### ISSUE TITLE
Auto-Sizer not working with Variable-Sized-Gird 

### ISSUE THREAD

**Issue by sgupta317** [bvaughn/react-window#399]
I am having an issue using Auto-Sizer with Variable-Sized-Grid table is not creating while wrapping Grid into Auto-Sizer it showing blank rows, can you please share some example were you have used with Variable-Sized-Grid.

Thanks in Advance.

**Comment by bvaughn** [comment]
The docs already show an example of using auto sizer:
https://github.com/bvaughn/react-window#can-a-list-or-a-grid-fill-100-the-width-or-height-of-a-page

There is no difference between whether it's used with list or grid.

If you're having trouble, please share a repro case that shows what you're trying so I can take a look. Else there isn't anything I can do to help. :smile:

I'm going to close this issue since it's not really actionable. We can keep talking here though.

**Comment by sgupta317** [comment]
Hi bvaugn, Thanks for your reply.

Please find the below codesendbox link, to get the complete example where i put AutoSizer with VariableSizedGrid.

codesendbox link : [https://codesandbox.io/s/zen-visvesvaraya-7rxk2]

Here I have put autoSizer for both hearder and content grid and checked, sometime width is not calculating proper and some time grid does not render.

In case there are only one row(like header row) then grid does not render.

Please suggest.

**Comment by sgupta317** [comment]
Hi bvaughn, Thanks for your reply.

Please find the below codesendbox link of my code where i have used AutoSizer with VariableSizedGrid.

codesendbox link : https://codesandbox.io/s/zen-visvesvaraya-7rxk2

here i have put AutoSizer for both header gird and content grid, some time width is not calculation properly and somethime grid is not rendering to the dom.

Please suggest.
In case of only one row(header row) some grid does't render.

**Comment by bvaughn** [comment]
I don't know how to use this demo. At a glance, it seems to render everything ok.
