### ISSUE TITLE
scollbar shrinks when scrolling down when items height are large

### ISSUE THREAD

**Issue by hbinkle** [bvaughn/react-window#408]
Hi,
As soon as the item height ist large, e.g. 100px the scrollbar shrinks on scrolling down.
So you can't scroll to the end of the list when bottom of the list is at bottom of the window.

I simplified your demoto show the issue:
[codesandbox](https://codesandbox.io/s/focused-chatelet-t483q?fontsize=14&hidenavigation=1)

**Comment by bvaughn** [comment]
This is the way it's designed to work. `VariableSizeList` uses estimated sizes for list items initially to avoid having to explicitly measure them all. As a user scrolls through content, and more list items are _actually_ measured, the total scroll size is updated gradually. For large lists, this usually isn't noticeable because the update is so small each time. In your example it's more noticeable because there are only a few rows, and the delta between the actual size (100px) and the default estimated size (50) is largeish.

You can improve the accuracy of the estimate (if you'd like) by specifying your own [`estimatedItemSize ` property](https://react-window.now.sh/#/api/VariableSizeList) in this case.

Here's a graphic I made that illustrates what's happening in case it's helpful:
![screen shot 2017-03-20 at 1 30 58 pm](https://cloud.githubusercontent.com/assets/29597/24120343/7abf4794-0d71-11e7-9ac2-77efd36dd5e5.png)
