### ISSUE TITLE
Conditionally disable scrolling without losing scroll bar?

### ISSUE THREAD

**Issue by tadeolinco** [bvaughn/react-window#409]
Wouldn't want to remove the scroll bar as it messes up the layout.

The usual hack I do was adding a `scroll` event listener that resets the `scrollTop` of the container to whatever it was before disabling scroll.

I try to do this now with the `outerElement` and I see that the scroll bar does indeed not change position, but the contents of the `FixedSizeList` still move.

Not a feature request, just a question if it's possible or there's a hack around it. 

Any help is appreciated. :smiley:

**Comment by bvaughn** [comment]
Hello there.

I don't know if this is possible. It's not a use case this library supports though, or that I'd want to add support for, so you're kind of on your own if you want to try to make it work. 😅

You might try asking somewhere like Stack Overflow?

I'm going to close this issue since it's not really actionable. 🙇‍♂️ Good luck!
