### ISSUE TITLE
Alternate "smart" scroll align mode that always centers when item is out of viewport

### ISSUE THREAD

**Issue by Livven** [bvaughn/react-window#422]
Is there any interest in adding an additional scroll align mode that behaves similarly to `smart`, except that it always centers the item if it is out of the viewport regardless of the distance? The only case where it would scroll as little as possible would be if it was only partially in the viewport. I think this feels a bit more natural.

The documentation for the `align` parameter of `FixedSizeList.scrollToItem` would look like this (compared to `smart`):

> - If the item is already visible, don't scroll at all.
> - If it is ~~less than one viewport away~~ _partially in the viewport_, scroll as little as possible so that it becomes visible.
> - If it is ~~more than one viewport away~~ _outside of the viewport_, scroll so that it is centered within the list.

And the code for `getOffsetForIndexAndAlignment` would switch `size` for `itemSize` ([adapted from here](https://github.com/bvaughn/react-window/blob/51a24c4972c9ca5eee4df5ea3ec25bc4328e40c5/src/FixedSizeList.js#L41)):

```js
if (align === 'alternate-smart') {
  if (
    scrollOffset >= minOffset - ((itemSize: any): number) &&
    scrollOffset <= maxOffset + ((itemSize: any): number)
  ) {
    align = 'auto';
  } else {
    align = 'center';
  }
}
```

If you are not against adding such an option (name tdb 😉) I could create a pull request.

**Comment by battesonb** [comment]
I have a use case for preferring smart scroll behavior but aligning to the top of the element. I see there are a lot of outstanding PRs in this repo, otherwise I would contribute.

As it is currently, it seems like there would be a lot of variation to alignment such as smart (current), smart-center, smart-start, smart-end. Ideally, the scroll behavior and alignment should be different options, but that would require a major version bump. Something like:

```ts
gridRef.current.scrollToItem({
  scrollBehavior: "always" | "minimum" | "smart",
  align: "start" | "center" | "end"
});
```

**Comment by wrobbinz** [comment]
+ 1 to this suggestion. Would love to see this behavior made available.

Having played with the `smart` option, I think the behavior of sometimes centering and sometimes scrolling the minimum amount feels like inconsistent behavior, and so is a little disorienting. I can empathize with the intention of this option: that if the user is close to the (out-of-view) item, that scrolling the bare minimum could be less disorienting. But to me, the more straightforward behavior is:

- item in view? no scroll
- item out of view? center it

(This is VS Code's behavior so that is likely why this behavior feels so right to me)
