### ISSUE TITLE
OverscanRowCount Causes A Lot of Unecessary Mounts

### ISSUE THREAD

**Issue by iansullivan88** [bvaughn/react-window#427]
If overscanRowCount is set on a FixedSizeGrid, rows above the current viewport are repeatedly mounted. 

To reproduce:

1. Visit https://codesandbox.io/s/fixedsizegrid-overscan-uyzl8
2. Scroll to row 300
3. Open the console
4. Scroll down by a single row

**expected console output:**
Mount 364

**actua console outputl:**
Mount 364
Mount 250
Mount 251
Mount 252
Mount 253
Mount 254
Mount 255
Mount 256
Mount 257
Mount 258
Mount 259
Mount 260
Mount 261
Mount 262
Mount 263
Mount 264
Mount 265
Mount 266
Mount 267
Mount 268
Mount 269
Mount 270
Mount 271
Mount 272
Mount 273
Mount 274
Mount 275
Mount 276
Mount 277
Mount 278
Mount 279
Mount 280
Mount 281
Mount 282
Mount 283
Mount 284
Mount 285
Mount 286
Mount 287
Mount 288
Mount 289
Mount 290
Mount 291
Mount 292
Mount 293
Mount 294
Mount 295
Mount 296
Mount 297
Mount 298

My real application has about 20 columns and each cell contains images so this causes a fairly large performance hit.

**Comment by bvaughn** [comment]
Do do you have `overscanRowCount={50}`? This is what's currently causing the large number of items to render.

**Comment by iansullivan88** [comment]
I use overscanRowCount in my real application although it isn't set as high.

Is it correct that after the initial render, scrolling by one row should only cause one new row to mount regardless of the overscanRowCount setting?

Thanks for looking at this.

**Comment by bvaughn** [comment]
I'm not *really* looking at it to be honest 😅 I don't have the bandwidth right now. Maybe someone else would be interested in looking into it, although I've already started a v2 rewrite so it might be better to look at that instead.

I mentioned the overscan issue just in case you didn't know :)

I'm swamped with React and React DevTools stuff these days and this library rarely gets my attention because I just don't have the time :(

**Comment by iansullivan88** [comment]
No problem. I'll maybe take a look at fixing it if I get some time!

**Comment by piecyk** [comment]
@iansullivan88 it's not a bug, but by design optimisation. When scrolling in one direction opposite side will set overscanCount to `1` till stop then back to passed value. 

https://github.com/bvaughn/react-window/blob/master/src/createGridComponent.js#L666-L673 

That's why you are seeing those mounts before visible index when you scroll just bye one index down.

**Comment by iansullivan88** [comment]
I see - the optimization results in fewer items on the page while scrolling but it comes at the cost of re-creating elements at the end of a scroll.

The items in my application are cheap to render and expensive to mount so the following behaviour would be optimal for me:

`const overscanBackward = Math.max(1, overscanCountResolved);`

It's not worth digging into unless there is any other interest in this so I'll close the issue.

Thank you!
