### ISSUE TITLE
Item never appear if scrolling to fast

### ISSUE THREAD

**Issue by kennetpostigo** [bvaughn/react-window#44]
This snippet below stops rendering items if I scroll to fast. Not sure why, The list I have right now while in dev is about 1600 elements. However the real list will be at the minimum 400k elements. There are no errors in the console that can point to any reason why this might be happening.

```js
<div>
  <h2>
    Results(
    {listItems.length})
  </h2>
  <List
    itemCount={listItems.length}
    itemSize={50}
    height={this.state.height}
    width={400}
  >
    {({ index, style }) => (
      <div
      style={style}
      className={css(styles.searchItem)}
      style={styles}
    >
      <p>{listItems[index].properties.id}</p>
      <p>Score: {listItems[index].properties.score}</p>
    </div>
    )}
  </List>
</div>
```
![react-window](https://user-images.githubusercontent.com/8888991/44167329-df357e00-a09b-11e8-8704-468667a868c2.gif)

**Comment by bvaughn** [comment]
```js
    {({ index, style }) => (
      <div
      style={style}
      className={css(styles.searchItem)}
      style={styles}
    >
```

Remove `style={styles}`

I assume that's the bug. If it's not, please provide a runnable repro case in Code Sandbox and we can re-open

**Comment by kennetpostigo** [comment]
@bvaughn removed all the styles and it persists. Not sure why it happens and it doesn't seem to happen on your demo app.

**Comment by bvaughn** [comment]
Don't remove _all_ the styles 😄A list item needs a style to work.

The problem with your example above is that you defined the `style` attribute twice, and the second one (which would override the first one) referred to a variable/value that didn't exist (`styles` rather than `style`).

Anyway, like I said– please provide a runnable repro case in Code Sandbox if the bug persists, but I'm pretty sure it's that attribute 👍
