### ISSUE TITLE
Is there any way to hide horizontal scrollbar on systems/browsers with always visible scrollbar?

### ISSUE THREAD

**Issue by gonuit** [bvaughn/react-window#448]
A horizontal scrollbar indicates that there is a space below the vertical scrollbar 🤔. The horizontal scroll bar is displayed always when the vertical bar is present. 

I am using `react-virtualized-auto-sizer` package to achieve Grid width equal 100vh.

![image](https://user-images.githubusercontent.com/37882650/78589481-8a321700-7840-11ea-93f1-3af8c9d8acd5.png)

**Comment by matthewma7** [comment]
This is a very common behavior related to the scrolling bar. I would try set `overflow-x: hidden;`

**Comment by martynaskadisa** [comment]
Looks like a duplicate of an issue I encountered some time ago https://github.com/bvaughn/react-window/issues/65

Your described behavior happens because vertical scroll bar also takes up space and it's more than your specified grid width. You'll need to take into account the OS scrollbar width and adjust your grid width accordingly.

There's a neat trick/hack to calculate scrollbar dimensions:
https://stackoverflow.com/questions/13382516/getting-scroll-bar-width-using-javascript

**Comment by gonuit** [comment]
Thank @matthewma7 and @martynaskadisa for your answers 🔥 
I was hoping that there is some magic argument or popular solution for that type of issue 😃😕.

I think that this issue could be closed as all needed informations was provided 😄
