### ISSUE TITLE
Support scrolling with Page Up / Page Down keys

### ISSUE THREAD

**Issue by steverandy** [bvaughn/react-window#46]
Currently scrolling with Page Up / Page Down is not possible after you click on the list item.

**Comment by bvaughn** [comment]
That's correct. Currently, you will need to implement this yourself adding a custom key event handler to a DOM element somewhere above list (or grid) and using the scroll-to API, e.g.:

```js
handleKeyDown = event => {
  switch (event.keyCode) {
    case 33: // page up
      this.listRef.current.scrollTo(
        this.state.scrollOffset - listHeight
      );
      break;
    case 34: // page down
      this.listRef.current.scrollTo(
        this.state.scrollOffset + listHeight
      );
      break;
};

handleListScroll = ({ scrollOffset }) =>
  this.setState({ scrollOffset });
```

I don't _think_ I want to build this into the library, but I'm not dead set against it. If you'd like to submit a PR (with docs and tests) to add it, I will be happy to review and give it consideration 😄

For now, I'm going to close this issue since I don't intend to take action on it though!

**Comment by vishnu0320** [comment]
**this.listRef.current.scrollTo is not a function**

**Comment by pastelmind** [comment]
After much experimentation, I concluded that manually calling `scrollTo()` and/or `scrollBy()` is unpleasing and difficult. Scrolling with JavaScript is very janky; with `behavior: 'auto'`, the browser instantly changes the scroll position w/o animations. This destroys the UX when pressing Page Up/Down (where am I?).

However, using `behavior: 'smooth'` opens a whole can of worms. When the user holds down the Page Up/Down key, the `scrollTo()` calls quickly pile up and overload the browser. I tried various debouncing strategies: lodash's `throttle()` function; a hand-written one based on `setTimeout()` and `requestAnimationFrame()`; and finally, one that used React refs. None of them were successful in recreating a smooth scrolling experience.

I pulled out my hair over this. I even went back to `react-virtualized` because its `<Table>` component has no problem with smooth scrolling. As it turns out, setting `tabIndex` on the outer (container) component and relying on the browser's native scrolling behavior is the best in terms of UX:

```jsx
<FixedSizeList
  itemCount={items.length}
  itemData={itemData}
  itemSize={60}
  outerRef={(elementRefOrNull) => {
    if (elementRefOrNull) {
      elementRefOrNull.tabIndex = -1;
    }
  }}
>
  {/* ... */}
</FixedSizeList>
```

**Comment by annslittleflower** [comment]
in case somebody is interested in arrow navigation solution
removed lots of code because thats a code from commercial project
but you only need to look at handleKeyDown function, all magic is there


`

import { FixedSizeList } from 'react-window'
import React, {useCallback, useRef, useState, useEffect} from 'react'

const TAB_KEY_CODE = 9
const ENTER_KEY_CODE = 13
const ARROW_UP_KEY_CODE = 38
const ARROW_DOWN_KEY_CODE = 40

const LIST_HEIGHT = 31 * 6

const TheComponent = ({
  onChange,
  value,
}) => {
  const selectedCountryIndex = value || undefined

  const ref = useRef(null)
  const optionsRef = useRef(null)
  const labelRef = useRef(null)
  const innerListRef = useRef(null)
  const outerListRef = useRef(null)

  const [focus, setFocus] = useState(false)
  const [keyboardSelectedKey, setKeyboardSelectedKey] =
    useState(selectedCountryIndex)
  const [isInitialScrollSet, setIsInitialScrollSet] = useState(false)

  const selectCountryWithKeyboard = (increment) => {
    if (keyboardSelectedKey === undefined) {
      setKeyboardSelectedKey(0)
      return
    }

    const lastIndex = countries.length - 1
    const newKey = keyboardSelectedKey + increment

    if (newKey < 0) {
      setKeyboardSelectedKey(0)
      return
    }

    if (newKey > lastIndex) {
      setKeyboardSelectedKey(lastIndex)
      return
    }

    setKeyboardSelectedKey(keyboardSelectedKey + increment)
  }

  const setFocused = useCallback(() => {
    setFocus(focus)
  }, [setFocus, focus])

  useEffect(() => {
    if (!focus) {
      if (selectedCountryIndex === undefined) {
        setKeyboardSelectedKey(undefined)
      }

      if (selectedCountryIndex > -1) {
        setKeyboardSelectedKey(selectedCountryIndex)
      }

      setIsInitialScrollSet(false)
      return
    }

    if (!isInitialScrollSet) {
      const scrollToY =
        outerListRef.current.scrollTop === 0 && keyboardSelectedKey
          ? styledOptionHeight * keyboardSelectedKey + 1
          : 0

      outerListRef.current.scrollTo(0, scrollToY)
      setIsInitialScrollSet(true)
    }
  }, [focus])

  const setUnFocused = useCallback(() => {
    setFocus(false)
  }, [setFocus])

  const handleKeyDown = (event) => {
    if (
      event.keyCode === ARROW_DOWN_KEY_CODE ||
      event.keyCode === ARROW_UP_KEY_CODE
    ) {
      event.preventDefault()
    }

    if (event.keyCode === TAB_KEY_CODE) {
      setFocus(false)
      return
    }

    if (event.keyCode === ENTER_KEY_CODE) {
      // your needed value to change here
      onChange(someValue)
    }

    switch (event.keyCode) {
      case ARROW_UP_KEY_CODE:
        if (!outerListRef.current) return

        outerListRef.current.scrollTop =
          outerListRef.current.scrollTop - styledOptionHeight
        selectCountryWithKeyboard(-1)
        break
      case ARROW_DOWN_KEY_CODE:
        setFocus(true)

        if (!outerListRef.current) return

        outerListRef.current.scrollTop =
          outerListRef.current.scrollTop +
          (keyboardSelectedKey === undefined || keyboardSelectedKey < 5
            ? 0
            : styledOptionHeight)
        selectCountryWithKeyboard(1)
        break
    }
  }

  return (
    <StyledContainer
      className={className}
      tabIndex={0}
      ref={ref}
      onFocus={setFocused}
      onKeyDown={handleKeyDown}
    >
      <StyledLabel ref={labelRef}>
        <span>{selectedCountry.code}</span>
      </StyledLabel>

      <StyledOptions
        onFocus={setFocused}
        onBlur={setUnFocused}
        ref={optionsRef}
        open={focus}
      >
        {focus ? (
          <FixedSizeList
            height={LIST_HEIGHT}
            itemSize={31}
            itemCount={countriesKeys.length}
            itemData={countriesKeys}
            innerRef={innerListRef}
            outerRef={outerListRef}
            scrollOffset={300}
          >
            {(({ index, style, data }) => {
                return (
                  <div style={style}>
                    <StyledOption
                      focus={keyboardSelectedKey === index}
                      // add some styling if selected
                      // isSelected={}
                      onClick={() => onChange(index)}
                    >
                    </StyledOption>
                  </div>
                )
              })}
          </FixedSizeList>
        ) : null}
      </StyledOptions>
    </StyledContainer>
  )
}

 

export default TheComponent

`

**Comment by mmontag** [comment]
Here is a nice code example of ArrowKeyStepper for anyone stumbling across this thread. I know this is not page up/page down, but closely related. 

https://codesandbox.io/p/sandbox/hungry-heisenberg-x9739j5v8q?file=%2Fsrc%2Findex.js%3A7%2C1-8%2C1&from-embed=

Source: https://blog.logrocket.com/react-virtualized-vs-react-window/#arrow-key-navigation-arrowkeystepper
