### ISSUE TITLE
List resets when parent component's state changes with Hooks

### ISSUE THREAD

**Issue by acrainier1** [bvaughn/react-window#483]
Hi,  

I have a List and Card component from react-window in Flashcards.js.
<Scroll.Flashcard/> is imported from KanjiData.js module.

Whenever an useState React hook updates in Flashcards.js the list scrolls back to the first item.

ABSTRACT STRUCTURE OF CODE
```
<AutoSizer>
  <List {...props}>
    <Card {...props}>
      <Scroll.Flashcard {...props} />
    </Card>
  </List>
</AutoSizer>
```

However, whenever an state INSIDE the <Scroll.Flashcard/> changes, KanjiData.js, the list stays put as expected.

 I am not defining the list elements inline.

ACTUAL CODE
```
const Card = ({ index, data, style }) => {
    const propsScrollFlashcard = {
      kanjiData: data.scrollKanjiSet[index],
      kanjiSideUp,
      // ReviewMessage
    }
    return (
      <div className='window-item' style={style}>
        <Scroll.Flashcard {...propsScrollFlashcard} />
      </div>
)};

const listRef = React.createRef();
  function jumpToMiddle() {
    kanjiSet
     ?  listRef.current.scrollToItem(50)
     :  Function.prototype();
};

function MobileWindow() {
    return (
      <div className='window-container'>
        <AutoSizer>
          {({ height, width }) => (
            <List
                className='window-list'
                layout='horizontal'
                width={width}
                height={580}
                itemData={{ scrollKanjiSet }}
                itemSize={width}
                itemCount={scrollKanjiSet.length}
                ref={listRef}
            >
              { Card }
            </List>
          )}
        </AutoSizer>
      </div>
    );
}
```

**Comment by davidlud** [comment]
This is how hooks are intended to work. 

If a parent state updates, it will re-render itself and every child of that parent. If the child state updates, only the child will re-render. This is why nothing happens when the state inside your flashcard changes. 

The 'scrolling' back you're talking about is just the re-rendering of MobileWindow(). Seems like somewhere along your code it is being re-rendered because it is a child of something. It doesn't seem like this is the full source code as I see no react useState hooks. 

One of the more common ways of solving this is managing state only on the child level. If this is not possible due to the architecture of your code, you can also use React.memo

React.memo prevents a child component from re-rendering even though the parent re-renders. Note this **ONLY** works if the **DATA** going into the child is still the same, and that parent state change affected something else. 

Code structure looks like this
```
const MyComponent = React.memo(function MyComponent(props) {
      return (
           <h1>content</h1>
     )
});
```

note: according to official react docs, this is used as a performance optimization and shouldn't necessarily be used to prevent re-render, as it can cause headaches down the road.

**Comment by acrainier1** [comment]
Thanks David.

Memorizing it doesn't prevent the re render in my case.

With that said, I prop down state from the parent to the child. The child <Scroll.Flashcard/> does NOT alter parents state, but it does consume it, and conditionally renders different things based on it.

Could this be why?

**Comment by acrainier1** [comment]
Hi, I'm just following up with my question. Thanks.
