### ISSUE TITLE
VariableSizeGrid: Use it with  CSS Grid

### ISSUE THREAD

**Issue by Benwick91** [bvaughn/react-window#509]
Hey,

I have a CSS Grid and use Styled Components,

For example my Grid looks like this:
```
const Grid = styled.div`
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(100px, 1fr));
  grid-auto-rows: auto;
  grid-gap: 15px;
  align-items: stretch;
  justify-items: stretch;
`;
```

Is it now possible to use react-window? Perhaps with the `VariableSizeGrid` and `AutoSizer`?

I can't get it to work. How can I get the `columnWidth`, `columnCount`, `rowCount` and `rowHeight`?.

Thank you so much!

**Comment by Spring3** [comment]
I had a similar question and from my understanding the only way would be to calcualte left, right, top, bottom based on column index and row index provided in the `children` of `FixedSizeGrid` or `VariableSizeGrid`.

Due to `absolute` positioning setting `display: grid` along with the css rules for rows and columns won't work anyway.
