### ISSUE TITLE
Is there any detail example on how to make a responsive virtualized react-table ?

### ISSUE THREAD

**Issue by richardhsueh** [bvaughn/react-window#524]
I tried to implement react-window with react-table, I successfully make it working, all the **functions** are working, but the style is all messed up. All those inline styles are so annoying. I simply can't alter the style to the way I want.

Any help would be appreciated. 🙇🙇🙇🙇

**Comment by thexpand** [comment]
@richardhsueh As far as I know, the inline styles come from `react-table`, not from `react-window`. When you use table virtualization with `react-table`, probably you'll want to use non-table elements, so instead of `table`, `thead`, `tbody`, `tr`, `th` and `td`, you should be using `div` elements to render your layout. Additionally, you'll probably need to add the `react-table`'s plugin-hook `useBlockLayout` or `useFlexLayout`, so that it looks and behaves like a table.
