### ISSUE TITLE
Force row to render regardless of scroll

### ISSUE THREAD

**Issue by jclem** [bvaughn/react-window#527]
There are certain circumstances in which it's useful to force a row to render, even though it may not be visible. This can be useful if an app maintains focus state on that row and one doesn't want to lose it when scrolling.

For example, consider an app where the user moves focus by arrowing up and down, changing `document.activeElement` by calling `focus()` in `useLayoutEffect` or something. Ideally, we don't lose this focus when scrolling, but that happens with virtualized rendering when the row containing that active element is destroyed.

Is there a way to do this in react-window? There may be a workaround outside of the library, but I haven't come up with anything, yet.

**Comment by omarish** [comment]
Yes. I spent a while figuring this one out, and ultimately the way I did it by passing a custom `itemKey` function `VariableSizeGrid`. That will force react to refresh the cell (because the key changes, it knows it's expired and needs to re-render), but I'd only use this strategy when all other options are exhausted.

**Comment by jclem** [comment]
I have a PR for this at https://github.com/bvaughn/react-window/pull/549

**Comment by WofWca** [comment]
Related: https://github.com/bvaughn/react-window/issues/508.
