### ISSUE TITLE
Sticky and animations 

### ISSUE THREAD

**Issue by assuncaocharles** [bvaughn/react-window#536]
Hey @bvaughn  

I have some questions and some issues while trying to implements some features and would love to get some help with it. 

1. Sticky 

The Sticky Header example is nice but it removes the item from the list so it's almost the same as setting the item with `position: absolute` and `top: 0px:`. With this it's not really taking advantage of the `position: sticky` so what I would like to try to achieve would be something like in this simple list example: https://codesandbox.io/s/list-sticky-example-5tpgq?file=/src/App.js

Going further on this, sticky position can also let us sticky items on the bottom, this become a little bit more tricky because by the nature of virtualization if some item wouldn't be in the viewport it will not necessary be in the DOM, so I would be lost to try to achieve something similar to this: https://codesandbox.io/s/list-sticky-topbottom-example-b3lqr?file=/src/App.js  where `item 30` is sticky on the bottom and top while with virtualization it wouldn't be in the DOM before scroll. 

2. Animations

I want to achieve what is shown in this gif in this issue also related to animation: https://github.com/bvaughn/react-virtualized/issues/657#issuecomment-321711427

But since our list are flat items I am a bit lost how can achieve this expand animation, I tried to use `innerElementType` and iterate via children wrap the elements in some sort of container and try to expand, but since the lib is working on the positions and setting top it kind of conflicts. This was my best shot: https://codesandbox.io/s/02xbc

Would really appreciate any guidance where to follow here.

**Comment by tarb** [comment]
RE 2, You can expand the items pretty easily by using VariableSizeList and changing the size of 1 of the rows. To animate it just put a css transition on top ie ```transition: top 250ms ease-in-out;``` on your row (the element you pass the style too). This animates all the other items down, as their top changes when your item's size become bigger. 
You may want to play with the ```overscanCount``` depending on how big your expanding element is, as newly rendered items that were pushed offscreen and un-rendered will jump back in when you close your expansion, and they get rendered again. Increasing the overscan a few, so that these items are still rendered out of view fixes this.

**Comment by jwalton** [comment]
One downside to `transition: top 250ms ease-in-out` is that `top` is not a property you can transition on and get hardware acceleration, so you'll likely end up with janky performance on many clients, especially mobile or if you have a lot going on (except possibly FireFox, which I think will hardware accelerate this anyways).

It would be better if react-window were to position elements with `transform: translate(x, y);` instead of `left: x; top: y`.  Then you could `transition: transform 250ms ease-in-out` and everything would be smooth and hardware accelerated.  You could parse the "props" that react-window passes you to fix this but... yuck.

@bvaughn Would you be opposed to a PR that changes this so we use `transform` to position elements instead of `left/top`?  Or maybe a PR that provides a `(left, top) => React.CSSProperties` so you can customize the properties that react-window passes to you?

**Comment by jwalton** [comment]
Oh... Actually, `left` and `top` appear to be integers already.  So you can do:

```
  const newStyle = {
    position: 'absolute',
    top: 0,
    left: 0,
    transform: `translate(${style.left}px, ${style.top}px)`,
    transition: 'transform 0.5s',
    width: style.width,
    height: style.height,
  };
```

If you want to support the height of an item changing, you need to make sure your overscan is high enough that items don't suddenly appear when an item shrinks.
