### ISSUE TITLE
Re-render the visible list

### ISSUE THREAD

**Issue by staticdreams** [bvaughn/react-window#567]
Hello, is there a way to force react-window to re-render (refresh) the visible list (or the whole list if partial list is not an option) ?

We have a list of items (actually it is a chat room) and some messages may be deleted or modified, changing the potential row height or even removing items from the list. After doing some I'd like to refresh the list so all the variable heights are recalculated again.

**Comment by jeannnemelanie** [comment]
Hi,

I have the same need. I have a list of items in a payload, some of them do not come with content and need to be lazy loaded after first render. They should not be in the SSR render because of it's personalized content linked to a user. 

So when I fetch the content of those items, my list is already rendered. After the fetch, the rendered rows of lazy content is updating on the viewport but the height if the row is still 0px.

I would like to be able to actually say to my list re-render the rows now that you have the right heights.

Thanks.

**Comment by plandem** [comment]
`resetAfterIndex` should be used to reset styles

**Comment by vl-ad** [comment]
Use the "itemKey" prop if your list is sorted or modified.
https://react-window.vercel.app/#/api/FixedSizeList

**Comment by jeannnemelanie** [comment]
Awesome! Thanks @plandem @vl-ad :)

**Comment by alexdemartos** [comment]
Not working either resetAfterIndex nor itemKey prop. Any detailed answer for this question? Thanks in advance.
