### ISSUE TITLE
VariableSizeGrid does not clear clear cache and does not reapply new styles

### ISSUE THREAD

**Issue by martynaskadisa** [bvaughn/react-window#57]
Everything works fine when `rowHeight` or `columnWidth` selectors never change, but when they do change, rows and columns that were already rendered do not get their styles updated.

I've created an example sandbox with AutoSizer for this issue:
https://codesandbox.io/s/2p1jrywm30

When width of the element changes, e.g. user changing width of the window, `AutoSizer` updates the width and height, but `VariableSizeGrid` does not refresh those values. I would expect that cache should be invalidated and new styles should be calculated and applied to the children.

**Comment by bvaughn** [comment]
The `VariableSizedGrid` provides a couple of instance methods you can use to invalidate its cache. These are listed [in the docs for that component](https://react-window.now.sh/#/api/VariableSizeGrid).

The grid doesn't invalidate cached sizes when the getter methods change because this would usually result in the cache being useless. (For example, in your Code Sandbox the `columnWidth` function changes every render– so grid would end up resetting its cache _every_ render.)

Instead it relies on you to let it know when the underlying data has changed.

Here's an update:
https://codesandbox.io/s/n7nkw8049m

**Comment by martynaskadisa** [comment]
Thanks for the updated sandbox! I eventually ended up using that but It’s a bit sad that we have to use imperative methods. Resetting the cache on getter change would be useful when wrapping this component with some sort of enhancer which would control when to rerender `VariableSizeGrid`, for example `connect` from `react-redux`. Unless I’m missing something?

**Comment by bvaughn** [comment]
> Resetting the cache on getter change would be useful...

Inline functions are just too common in my experience. Overwhelmingly the common case. I chose to make the common case perform better and make the failure case more obvious (rather than a potentially subtle cache over-invalidation).

You could create a HOC to auto invalidate if you wanted.
