### ISSUE TITLE
Dynamic item sizes for each rendered item when using a variable size list

### ISSUE THREAD

**Issue by ionutpetre** [bvaughn/react-window#582]
Hello,

First of all, thank you for providing this amazing library.

I'm trying to implement a infinite scroll using variable size list on items that have dynamic heights (imagine an item being a message that might have text on multiple rows, images etc. and I cannot know from start what's the height) but I cannot see a proper way to doing it. 

On the documentation I see just the use case of knowing from before what are the size breakpoints of the items:
https://react-window.vercel.app/#/api/VariableSizeList 

I tried some approaches but none of them worked for me:

- Measuring the items before rendering by the list renderer:
 https://medium.com/trabe/measuring-non-rendered-elements-in-react-with-portals-c5b7c51aec25 
 
- Attaching refs on each items and then use clientHeight
 https://tiagohorta1995.medium.com/dynamic-list-virtualization-using-react-window-ab6fbf10bfb2

Can you provide some guidance on how this use case can be implemented? 
Any other references / articles are also appreciated.

Thanks.

**Comment by ionutpetre** [comment]
Actually the code example from second link from above solved my problem.

I leave this direct link here for anyone who needs it:
https://codesandbox.io/s/react-chat-simulator-yg114?file=/src/ChatRoom/Room/Messages/Messages.js

**Comment by ViklasN** [comment]
> Actually the code example from second link from above solved my problem.
> 
> I leave this direct link here for anyone who needs it:
> https://codesandbox.io/s/react-chat-simulator-yg114?file=/src/ChatRoom/Room/Messages/Messages.js

This solution worked for me. Thanks!

**Comment by WebdevMerlion** [comment]
> Actually the code example from second link from above solved my problem

So. If i click **render 4500 items** button from example modified height of row stay same. How to avoid this? clientHeight of node still stay the same

**Comment by zalenskiSofteq** [comment]
Unfortunately `scrollToItem` to the last item doesn't work correct if batch messages (50) comes. It scrolls to somewhere at the bottom.

I've added a simple loop for create a batch of messages
https://codesandbox.io/s/react-chat-simulator-batch-messages-39s9df?file=/src/ChatRoom/Room/Room.js:391-442

Does someone have a solution?

**Comment by qianjiachun** [comment]
> Unfortunately `scrollToItem` to the last item doesn't work correct if batch messages (50) comes. Its scrolls to somewhere at the bottom.
> 
> I've added a simple loop for create a batch of messages https://codesandbox.io/s/react-chat-simulator-batch-messages-39s9df?file=/src/ChatRoom/Room/Room.js:391-442
> 
> Does someone have a solution?

hey, have you solved this problem? or any solution ? tks🙏

**Comment by zalenskiSofteq** [comment]
> 

I solved with 2 additional logic:
1. second call `scrollToBottom` in the `setTimeout`
1. add `requestAnimationFrame` in the `scrollToBottom`

Solution:
https://codesandbox.io/s/react-chat-simulator-batch-messages-solved-92shql?file=/src/ChatRoom/Room/Messages/Messages.js

**Comment by qianjiachun** [comment]
😯 thank you very much



---Original---
From: "Zalenski ***@***.***&gt;
Date: Fri, Aug 12, 2022 17:57 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [bvaughn/react-window] Dynamic item sizes for each rendered itemwhen using a variable size list (#582)




   
I solved with 2 additional logic:
  
second call scrollToBottom in the setTimeout 

add requestAnimationFrame in the scrollToBottom 
 
Solution:
 https://codesandbox.io/s/react-chat-simulator-batch-messages-solved-92shql?file=/src/ChatRoom/Room/Messages/Messages.js

**Comment by marcospulido** [comment]
> Actually the code example from second link from above solved my problem.
> 
> I leave this direct link here for anyone who needs it: https://codesandbox.io/s/react-chat-simulator-yg114?file=/src/ChatRoom/Room/Messages/Messages.js

Works like a charm!
thaks! :v:

**Comment by robertmiddlekauffmckinsey** [comment]
I implemented the second solution you listed for React Table, but when I sort or filter the table I am having trouble getting the rowHeight object to update.

Here is it with the sort broken. To recreate just sort the status column and you'll see that the row heights are constant. This is likely because useEffect is not firing which makes sense.
https://codesandbox.io/s/row-height-constant-after-sorting-kt1b51?file=/src/App.js

The react docs recommend using useCallback instead (https://reactjs.org/docs/hooks-faq.html#how-can-i-measure-a-dom-node), but when I do that, ListRef gets an error that it doesn't exist:
https://codesandbox.io/s/row-height-constant-after-sorting-with-callback-wn8tre?file=/src/App.js

Does anyone know what I might be missing or how I might fix this?

**Comment by ndronov** [comment]
does anyone know how to combine this solution with [react-window-infinite-loader](https://github.com/bvaughn/react-window-infinite-loader)?

**Comment by ndronov** [comment]
> does anyone know how to combine this solution with [react-window-infinite-loader](https://github.com/bvaughn/react-window-infinite-loader)?

**Comment by ndronov** [comment]
> Actually the code example from second link from above solved my problem.
> 
> I leave this direct link here for anyone who needs it: https://codesandbox.io/s/react-chat-simulator-yg114?file=/src/ChatRoom/Room/Messages/Messages.js

does anyone know how to combine this solution with [react-window-infinite-loader](https://github.com/bvaughn/react-window-infinite-loader)?

**Comment by nynevi** [comment]
for those who are trying to adapt the example to work with react-select's custom MenuList component, a couple of notes to you:
- do not swap useRef to useState as it causes a re-render
- on AutoSizer, specify style with `height: minHeight` using the example below
```
   const minItemHeight = 42
    const totalHeight = useMemo(
        () => minItemHeight * itemCount,
        [itemCount, minItemHeight],
    )
    const minHeight = useMemo(
        () => (totalHeight > maxHeight ? maxHeight : totalHeight),
        [totalHeight, maxHeight],
    )

    //...

    <AutoSizer
            style={{
                width: "100%",
                height: minHeight,
            }}
            className={"AutoSizer"}
        >
```

- adapt `getRowHeight` function to respect the `minItemHeight` you have
```
const getRowHeight = (index: number) => {
        const currentRowHeight = rowHeights.current?.[index]
        const height = currentRowHeight || minItemHeight
        return height
    }
```
- in the Row component, adapt the useEffect to take the child's height instead of the Row's height. otherwise there is overflowing on varying heights of options. because you are doing `currentRowHeight || minItemHeight`, it sets the style of the Row to have "height: minItemHeight" and next time `clientHeight` is checked, it reports the `minItemHeight` you have so there is no way to resize dynamic height options unless you check the height of the child inside the Row as such:

```
useEffect(() => {
            if (rowRef.current) {
                const firstChild = rowRef.current.firstElementChild
                if (firstChild) {
                    const height = firstChild.clientHeight
                    setRowHeight(index, height)
                }
            }
        }, [rowRef])
```

**Comment by tang4** [comment]
// perfect for me

useEffect(() => {
          setRowHeight(index, rowRef.current?.scrollHeight);

          return () => {
                 setRowHeight(index, undefined);
          };
}, [rowRef])
