### ISSUE TITLE
Root component updates trigger list remount

### ISSUE THREAD

**Issue by Rusya44** [bvaughn/react-window#59]
Is it expected behaviour?

![preview](https://user-images.githubusercontent.com/8863448/45667822-4d4de480-bb23-11e8-8af6-f6d17a104097.gif)

https://codesandbox.io/s/521oq1v574

**Comment by bvaughn** [comment]
This doesn't look like a "remount" – just a re-render of the `<div>`s. 😄

Let's use the [React profiler](https://reactjs.org/blog/2018/09/10/introducing-the-react-profiler.html) to take a look at [your sandbox](https://521oq1v574.codesandbox.io/):
![sandbox1](https://user-images.githubusercontent.com/29597/45694722-bed26680-bb14-11e8-8f61-f05693f4bfd6.gif)

The profiler shows us that each time the app re-renders, all of the list items re-render. This is because the list items are inline function components that get recreated each time your app renders:
![screen shot 2018-09-18 at 7 36 23 am](https://user-images.githubusercontent.com/29597/45695102-926b1a00-bb15-11e8-9ee8-56e7476e6b54.png)

This means that `List` will see them as a new `prop` value each time it renders (which will bypass its [`shouldComponentUpdate`](https://reactjs.org/docs/react-component.html#shouldcomponentupdate) checks).

Try moving the list item renders outside of your `App` render method, like so:
![screen shot 2018-09-18 at 7 39 11 am](https://user-images.githubusercontent.com/29597/45695293-f55cb100-bb15-11e8-84c2-a66132b53804.png)
![screen shot 2018-09-18 at 7 41 29 am](https://user-images.githubusercontent.com/29597/45695459-4a98c280-bb16-11e8-8ba8-49c72c68eb9c.png)

Now let's use the profiler to look at this [forked sandbox](https://n9z6lr0m2m.codesandbox.io/) where I did just that:
![sandbox-2](https://user-images.githubusercontent.com/29597/45694844-00fba800-bb15-11e8-801e-f2b7d7b6a202.gif)

The profiler shows us now that only your `App` component is re-rendering when you call `forceUpdate()`

Here's the source code for the forked sandbox:
https://codesandbox.io/s/n9z6lr0m2m

Maybe I should update the docs to avoid showing inline render methods. I tried to keep the docs brief so that they could be read easily but I can see how they might be misleading currently.

**Comment by bvaughn** [comment]
I have updated the docs to remove inline rendering functions! Hopefully this will avoid confusion in the future. 😅

**Comment by Rusya44** [comment]
Thank you for explaining. I really appreciate it 😄
