### ISSUE TITLE
After scrolling if you have any focused element in the list, it will lose focus

### ISSUE THREAD

**Issue by mmarzullotv** [bvaughn/react-window#650]
Hey guys, I got a Virtualized List that I want to add accessibility onto it, so by pressing the arrow keys you would move through the items up and down, for this, i need to focus on each of the items, but when I reach a certain point I lose the focus.

I just checked that in the official demo codepen: 
https://codesandbox.io/s/xenodochial-cdn-lnlw8t?file=/src/App.js

I added some inputs in there as a replacement but the idea is the same, check that if you have focused on any input, after scrolling a bit, and going back up, you will see the focus is no longer active on the element it's supposed to.

Do you have any idea on how to solve/fix this?

**Comment by mmarzullotv** [comment]
It seems that it's an issue with the list, i just can't find why this is happening.

Here's another example: https://codesandbox.io/s/2w8wmlm89p

And you don't even need a focusable element for this, just click on the grid, start pressing the arrow keys to any direction, go fast and eventually, the whole focus from the scrollable container will disappear, it falls back to body. 

At first i thought that could be a rendering time problem where if you go fast enough, it wouldn't let the elements to render and so an unfocus would be produced. So in my item list whenever i move up/down I make the list scroll to center that item specifically. But unfortunately, it didn't work. At some point the focus keeps going out of the container.

Any idea of what I can do to achieve this?

**Comment by zhouzi** [comment]
The way the virtual list works is that it only keeps in the DOM the items that are visible on screen. So what happens in your case is that you have the focus on an element that gets removed from the DOM when scrolling down.

**Comment by mmarzullotv** [comment]
@zhouzi exactly that's what's happening.

**Comment by tounsoo** [comment]
I would expect some callback so I can do something if the focus is blurred. Right now it is an accessibility issue because I can't get back to current focused item when scroll happens.

**Comment by tounsoo** [comment]
Just checking if this was automation moving it to close or if there was a decision to not do this.

**Comment by Sharoof-Khan-Torero** [comment]
I also have an issue!
Issue: Arrow Key Scrolling Not Working in react-select with react-window
I am experiencing an issue where I am unable to scroll through the react-select dropdown list using the up and down arrow keys when implementing react-window for virtualization. However, scrolling works correctly when react-window is not used.

Code Snippet: MenuList with Virtualization

const MenuList = React.memo(({ options, children, maxHeight, getValue }) => {
  const [value] = getValue();
  const height = Math.min(children.length * 40, maxHeight);
  const initialOffset = options.indexOf(value) * 40;

  return (
    <List
      height={options.length >= 8 ? maxHeight : height}
      itemCount={children.length}
      itemSize={40}
      initialScrollOffset={initialOffset}
      width="100%"
    >
      {({ index, style }) => <div style={style}>{children[index]}</div>}
    </List>
  );
});

Steps to Reproduce
Implement the MenuList as shown above.
Use the react-select component.
Attempt to scroll the dropdown list using the up and down arrow keys.
Expected Behavior
I expect to be able to scroll through the dropdown options using the up and down arrow keys, as is typical with dropdown menus.

Additional Information
Versions: "react-window": "^1.8.10" and "react-select": "^5.8.0",,.
Browser: Chrome
![with_react-window](https://github.com/user-attachments/assets/fdb88c68-a338-4481-894c-eabf2c90143c)
![without_react-window](https://github.com/user-attachments/assets/5a721f3d-6e66-459a-90f3-9334f7bfddf4)

**Comment by WofWca** [comment]
Basically a duplicate of https://github.com/bvaughn/react-window/issues/490.
