### ISSUE TITLE
FixedSizeList react 18 typescript problem

### ISSUE THREAD

**Issue by vladimir-palocko-myob** [bvaughn/react-window#654]
Hello, not sure where the problem lies, could not find any reasonable explanation and the typing looks good to me, however, I'm not a typescript expert.

When I try to upgrade to the @types/react@18.0.0 and @types/react-dom@18.0.0 I'm getting this error:

``` 
Its instance type 'FixedSizeList<any>' is not a valid JSX element.
The types returned by 'render()' are incompatible between these types.
Type 'import("/node_modules/@types/react-dom/node_modules/@types/react/index").ReactNode' is not assignable to type 'React.ReactNode'.
Type '{}' is not assignable to type 'ReactNode'.
```

If I downgrade back to React/React-dom 17, the error disappears.

Any help or hint will be highly appreciated.

**Comment by 15373313512** [comment]
I also have this problem. React17 is installed in the main project. When using @types/react-window, you will be prompted:
`Its instance type 'FixedSizeList<any>' is not a valid JSX element.
The types returned by 'render()' are incompatible between these types.
Type 'import("/node_modules/@types/react-dom/node_modules/@types/react/index").ReactNode' is not assignable to type 'React.ReactNode'.
Type '{}' is not assignable to type 'ReactNode'.`

**Comment by glenne** [comment]
You might be able to fix it by specifying a resolution in package.json so a mix of 17 and 18 types isn't present:

` "resolutions": {
    "@types/react": "18.0.9",
    "@types/react-dom": "18.0.4"
  }`

Also in scripts section:
`"preinstall": "npx npm-force-resolutions"`

Remove and reinstall react-window.  See https://www.npmjs.com/package/npm-force-resolutions

**Comment by J5** [comment]
For anyone currently running into this issue and finding this thread the resolution step above works though I use yarn so I did not use the preinstall script and just resolved to "18^". The reason for this is if you run `yarn why @types/react` you might notice that `@types/react-window` has a requirement on react 19. I'm not sure if this is because I am in a mono-repo or it defaults to the latest version of react. In any case forcing resolutions solves this and running `yarn why @types/react` will now show it depending on the correct version of react types.

**Comment by SimranDev** [comment]
If you're using TypeScript `strict` type checking. You need to cast it to type `unknown` first. Here is an improvised version of this [solution](https://github.com/bvaughn/react-window/issues/654#issuecomment-1170390472) from @danizord.
```typescript
import { ComponentType } from "react";
import { FixedSizeList as _FixedSizeList, FixedSizeListProps } from "react-window";

const FixedSizeList = _FixedSizeList as unknown as ComponentType<FixedSizeListProps>;
```
