### ISSUE TITLE
the demo website cant open from China user

### ISSUE THREAD

**Issue by zhangwei900808** [bvaughn/react-window#692]
https://react-window.now.sh/

**Comment by liyatang** [comment]
+1

**Comment by bvaughn** [comment]
I'm sorry. That sounds frustrating.

Unfortunately I don't have any control over domains or IP ranges China blocks. I'm using Vercel to host this project because it's free, convenient, and seems to work well.

I'd suggest maybe you could setup an alternate host for the docs for this site, given the source for the docs are all here.
