### ISSUE TITLE
Scroll synchronization of List and Grid lagging

### ISSUE THREAD

**Issue by TomasPlachy** [bvaughn/react-window#746]
Hi, first of all thanks for implementing a great and easy-to-use library. I cant get rid of one issue though - when I try to sync the scrolling of grid and list calling listRef.scrollTo() inside Grid's onScroll() function, the list lags behind.

You can see this unwanted behaviour in following example when you try dragging horizontal scrollbar:
https://codesandbox.io/s/react-window-scrollto-issue-jxq838?file=/src/App.tsx

**Comment by Charles-XD** [comment]
Hi, I used 'react-custom-scrollbars-2' for syncing the scroll of two list and it works very well.

**Comment by AlanQtten** [comment]
> Hi, I used 'react-custom-scrollbars-2' for syncing the scroll of two list and it works very well.

hi, do you have a demo about this situation? I use `react-custom-scrollbars-2` wrap my VariableSizeList, and the `onScroll` of `react-custom-scrollbars-2` won't call at all

**Comment by 99Arrzel** [comment]
@AlanQtten Did you fix it?

**Comment by bvaughn** [comment]
If you use native scroll, there will be sync issues between the two scrollable items. I suspect the third party package (`react-custom-scrollbars-2`) uses some custom/synchronous scrolling approach which avoids these, but at the cost of potentially making the main scroll feel less responsive.

Going to close this issue since I don't think scroll-syncing is within scope of this library.
