### ISSUE TITLE
onScroll happens without user action

### ISSUE THREAD

**Issue by avin** [bvaughn/react-window#78]
Seems `onScroll` fires every time on mount without user action with params:
```
scrollDirection: "forward"
scrollOffset: 0
scrollUpdateWasRequested: false
```
demo https://codesandbox.io/s/7jkw0p7490

**Comment by bvaughn** [comment]
This is actually an intentional design decision, although maybe I should make it clear that it's expected in the docs. The reason for this is that sometimes there is important logic in a scroll handler that needs to be run _at least once_ to initialize values or scroll-sync some other component. In my own experience (with react-virtualized, which also implements this pattern) it's _more_ confusing for the `onScroll` prop not to be called initially, although I understand why this could be confusing too.

I'm going to close this issue for now– because the described behavior is intentional– but let's keep talking about it if you disagree that it's a good choice!
