### ISSUE TITLE
React-window List + Autosizer, Scroll event does not get triggered

### ISSUE THREAD

**Issue by MatteoGioioso** [bvaughn/react-window#91]
I am using React-window List in conjunction with Autosizer and a custom WindowScroll HOC.
My use case is a typical infinite scroll that loads content continuously as the user scrolls down the page.

This is the code sandbox to reproduce the case:
https://codesandbox.io/s/j4rypqozrv

As you can see the `scroll` event does not get invoked.
However if I set the `height` of the list manually and `style={{overflow: 'hidden'}}`, the event will get triggered.

**Comment by bvaughn** [comment]
Ah, I see.

This doesn't look like it has anything to do with react-window at first glance. The thing you're adding a "scroll" event to isn't even a react-window component, but a container that renders a `<div>` around it.

If you wanted to tap into the list scroll event, why not just use the list's `onScroll` callback? [From the docs](https://react-window.now.sh/#/api/FixedSizeList):

> **onScroll: function**
> Called when the list scroll positions changes, as a result of user scrolling or scroll-to method calls.

```js
function onScroll({
  scrollDirection,
  scrollOffset,
  scrollUpdateWasRequested
}) {
  // scrollDirection is either "forward" or "backward".
 
  // scrollOffset is a number.
 
  // scrollUpdateWasRequested is a boolean.
  // This value is true if the scroll was caused by scrollTo() or scrollToItem(),
  // And false if it was the result of a user interaction in the browser.
}
```

[Here is an example fork of your Code Sandbox](https://codesandbox.io/s/93vwkw5ryp).

Hopefully this is enough to get you going but if not, let's keep chatting here. 😄 Going to close this for now though because I think it's been answered.

**Comment by MatteoGioioso** [comment]
> This doesn't look like it has anything to do with react-window 
In fact it does not, the problem, as I have mentioned, is the Autosizer component. 
`if I set the `height` of the list manually and` style={{overflow: 'hidden'}}`, the event will get triggered.`

I can use my WindowScroll normally with any react-window components as long I specified the height myself. If not the event does not get triggered, no matter where I add it.

I did not want to use the `onScroll` callback because I have already implemented my own HOC and I did not want to change my logic. I have quite many lists some virtualized and some none. 
Unfortunately I have a case in which I cannot calculate the total height (I am using VariableSizeList component)

**Comment by bvaughn** [comment]
>> This doesn't look like it has anything to do with react-window
>
> In fact it does not, the problem, as I have mentioned, is the Autosizer component.

Fair enough, although you filed this issue in the react-window repository 😄

**Comment by bvaughn** [comment]
Can you recreate the behavior you're looking for– (an element with a fixed height, that bubbles "scroll" events to `window` when scrolling)– using plain HTML and JavaScript?

**Comment by MatteoGioioso** [comment]
So basically yes, if the height is coming from the Autosizer, the **scroll event** does not get triggered, if a custom height is used instead it does work.
Is this behavior expected?

**Comment by bvaughn** [comment]
I'm not sure I understand your answer to my previous question:
> Can you recreate the behavior you're looking for using plain HTML and JavaScript?

Can you clarify?

**Comment by MatteoGioioso** [comment]
The clarification is that I would like to use the scroll from the body, not the one from react-window.

**Comment by bvaughn** [comment]
Ah. react-window does not have a mode like [react-virtualized's `WindowScroller`](https://bvaughn.github.io/react-virtualized/#/components/WindowScroller) where it can be driven by the window's scroll event. At this point, I'm not convinced it's worth the added complexity and maintenance burden for something that's not used often. I may reevaluate this in the future if it's a common request.

**Comment by MatteoGioioso** [comment]
Any chance I could use it with React-window?

**Comment by bvaughn** [comment]
It wouldn't work. `Grid` and `List` components in `react-virtualized` need to support a special passive mode where they overflow their visible content and accept controlled scroll offsets. This adds complexity to the components (not a ton but it's not free) and I haven't added a similar functionality to `react-window` because I don't think it's a common enough use case to warrant.

**Comment by MatteoGioioso** [comment]
Ah, I see, what a pity, I have to move to react-virtualized then
