### ISSUE TITLE
Support nested arrays

### ISSUE THREAD

**Issue by Avivhdr** [bvaughn/react-window#93]
Hi,
Is there a plan to support nested arrays with children?
like in [infinite-tree](https://github.com/cheton/infinite-tree) or [react-virtualized-tree](https://github.com/diogofcunha/react-virtualized-tree).

**Comment by bvaughn** [comment]
react-window only knows about the number of items in a list— not whether it's an array or a Set or whether it's nested, etc. So technically, what you're asking about could already work, but you would need to do some work to "flatten" the array.

I have no plans to create a tree component as part of this library though, no. The one you linked to could be refactored to support react-window pretty easily though I would imagine.

**Comment by Avivhdr** [comment]
@NeekSandhu Looks amazing! I would love to try it out.
The documentation is not so clear though. is it work-in-progress?

**Comment by NeekSandhu** [comment]
@Avivhdr `react-aspen`, at least the core (besides fancy features like drag and drop etc.) is solid as a rock, and production ready.

It's a pity that documentation isn't great. Something I hate myself. You see, this project is written in TypeScript and the dependencies are split into separate projects. I'm using TypeDoc to generate documentation, which is terrible at doing that one job.

I was hoping I would give TypeDoc an entry point (`react-aspen/src/index.ts`) and it'd automatically walk the import/export graph and document all the stuff it finds in the process (including the said dependencies). But unfortunately, it doesn't work that way leading to a shit documentation.

___

The recommended way to consume `react-aspen` is not `npm i react-aspen`, but instead fork off of [`react-aspen-demo`](https://github.com/NeekSandhu/react-aspen-demo) which has most features implemented and ready to go. And from there, you can see how the API is used.

Once `react-aspen` is in your project, then if you're using VSCode, it's intellisense will explain every function/method call as you go!

___

@bvaughn 

Many thanks, Brian! If you do use it, consider `git submoduling` [`react-aspen-demo`](https://github.com/NeekSandhu/react-aspen-demo) instead of having to deal with low-level stuff from scratch.

___

To leverage Aspen's potential to the fullest, I recommend getting to know it's family:

 - [`aspen-decorations`](https://github.com/NeekSandhu/aspen-decorations) Styling engine for flattened nested trees
 - [`aspen-tree-model`](https://github.com/NeekSandhu/aspen-tree-model) State container for everything `react-aspen` (this comes with `TreeStateWatcher` that let's you save the current state of Aspen tree, like all expanded directories and scroll position)
 - [`aspen-core`](https://github.com/NeekSandhu/aspen-core) The thing that "manages" flattened representation of nested trees and supervises moving/adding/removing items on the fly.
