### ISSUE TITLE
Cannot seem to prevent re-rendering of items on render of parent component

### ISSUE THREAD

**Issue by wilcoschoneveld** [bvaughn/react-window#94]
Hey!

In our use-case it is very expensive to render an item (a document page) so I am looking to optimise as much as possible. What I am looking to achieve is a memoization of list items when parent state is changed. Unfortunately it looks like rendering the parent always re-renders the visible children, even if the props are the same.

E.g. in the following example clicking the red div will trigger a re-render of the children: https://codesandbox.io/s/qk50n4x7qw

In your [memoized list example](https://codesandbox.io/s/github/bvaughn/react-window/tree/master/website/sandboxes/memoized-list-items) you can see the same happening.

Any ideas on what is going on? Is this desired behaviour possible?

Thanks a lot!

**Comment by bvaughn** [comment]
Visible items only re-render (on click) in my memoized example because the `itemData` wrapper object is recreated (because I recreate the `items` array rather than mutating it)– so the props passed to the item renderers _do_ change (specifically the `data` prop).

@TrySound is correct that your demo's `renderItem` component is a function, so it's expected that it will always re-render. Using `useMemo` or `PureComponent` like in my example should fix this.
