### ISSUE TITLE
`onItemsRendered` isn't called if memoized args for callback function happen to be the same

### ISSUE THREAD

**Issue by gpmcadam** [bvaughn/react-window#99]
If you change the value of `itemCount` and `itemData` (e.g. dynamic filter a list), the `onItemsRendered` callback doesn't fire if the `itemCount` is the same, even if the `itemData` is different.

This is due to the fact that the arguments are simply memoized, and because none of the arguments change in the callback (if all items are visible, for example) then it won't call it again.

See: https://github.com/bvaughn/react-window/blob/master/src/createListComponent.js#L305

**Comment by bvaughn** [comment]
> This is due to the fact that the arguments are simply memoized, and because none of the arguments change in the callback (if all items are visible, for example) then it won't call it again.

This is intentional. Neither `onScroll` nor `onItemsRendered` are called unless their params have changed. I do this so that application developers don't have to add their own level of memoization _on top of_ these callbacks to avoid performance pitfalls. (My general approach with this library is to avoid potential performance problems when ever possible.)

Given the name of this prop ("items rendered") I can see why you might anticipate the callback being called again when `itemData` changes. Maybe a more accurate name would be something more like "item indices change" but I guess that ship has sailed. 😄

Maybe you can explain more about your use case? Same code is usually helpful too.

The existing callbacks let your code hook into things you would otherwise have a hard time observing. In the case of `itemData`– this is something your code creates/recreates, so it seems like you can already detect this case without react-window's help.

My current thinking is that the prop is fine as is, although I will update the documentation to make the expected memoization behavior more explicit. For now I'm going to close this issue too, because I don't plan on taking any action on it (other than a docs change which I'll make right now.)

Let's keep talking though. I'd like to learn more about your use case. If necessarily, I'll re-open the issue.

**Comment by gpmcadam** [comment]
Thanks for the response, @bvaughn  - appreciate your comments and hopefully we can continue the discussion and maybe there's something about my implementation that I can change to get the same effect.

I've prepared a codesandbox to demo the issue I'm having with instructions inline on how to best replicate it. Hopefully this is enough to demonstrate what I'm getting at.

https://codesandbox.io/embed/jl01j488v9?expanddevtools=1&moduleview=1

Thanks again for taking the time to respond, much appreciated.

**Comment by bvaughn** [comment]
Of course. Happy to discuss. 😄

Here's what I was thinking along the lines of:
https://codesandbox.io/s/rypzyzmop

Since your component is updating the `itemData` (in essence) then it knows when _that_ part has changed. In my mind, `onItemsRendered` is meant to be more of an `onScroll` alternative (if all you really care about is the indices, not the scroll offset).

**Comment by dcporter** [comment]
This sounds fine, but there's an edge case with infinite-loader: I'm switching from an array with the visible range loaded, to an array where the visible range not loaded. `onItemsRendered` isn't being called and `isItemLoaded` isn't being called, so `loadMoreItems` never gets called and I never load more items. The workaround would require me to separately track visible range in order to trigger the request, but some combination of react-window and infinite-loader should be handling this case.
